{
  "hash": "6870680ecbd1b0cb820a4f84fddc0854",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Módulo 4: Inferencia Estadística\"\nauthor: \"Gerardo Esteban, Gómez-Santiago\"\ndate: \"2026-08-14\"\ncategories:\n  - Curso R\n  - Bases de datos\n  - Visualización\n  - Estadística\ntoc: true\nformat: \n  html:\n    code-links:\n      - text: Video YouTube\n        icon: camera-reels\n        href: https://youtu.be/tOZHymuvgmE\n      - text: Repositorio GitHub\n        icon: file-code\n        href: https://github.com/GomezGerardoEsteban/Tidyverso/tree/main/TallerR/Modulo4\n    mathjax: default\n    code-tools: true\n    self-contained: true\nexecute:\n  warning: false\nimage: \"modulo4.png\"\n---\n\n## Introducción\n\nLa inferencia estadística es la búsqueda de parámetros poblacionales a partir de la información muestral a la que tenemos acceso.\n\nCómo es usual en análisis de datos en ciencias sociales *(también en casi todas las disciplinas científicas, no solo en las sociales)*, los datos disponibles se corresponden con muestras poblacionales que, si fueron seleccionadas de manera **ALEATORIA**, nos permiten hacer inferencias respecto al comportamiento o los valores paramétricos de la población.\\\nEn general no tenemos acceso a toda la información sobre algo que queremos medir, cuando es así, la inferencia estadística no hace falta, pero como casi nunca es así, es fundamental conocer las nociones básicas de inferencia estadística.\n\nPensemos en un ejemplo, creemos que en las ciudades capitales por ser capitales el promedio de ingreso de la población es mayor al de ciudades que no son capitales. Para corroborar esa creencia, tendríamos que conocer los ingresos de todos los habitantes tanto de la ciudad capital que estemos analizando (Ej. Bogotá) como de las otras ciudades, eso es una ardua tarea que requiere toda la capacidad del Estado, no solo por cobertura, sino también por consideraciones éticas y normativas (*¿porque tendríamos la obligación de contestar preguntas respecto a nuestro ingreso o modos de vida?*). Esa tarea el Estado la realiza con cierta periodicidad (entre 4 y 10 años) en lo que se conoce como **CENSOS**.\\\nSin embargo, la periodicidad entre censos es muy larga y se requiere información sobre características poblacionales para por ejemplo, tomar decisiones de política pública en salud, educación, vivienda, etc.\\\n\nEs ahí donde entran las encuestas permanentes de hogares, aquellas que se realizan con mayor frecuencia sobre una **muestra** de la población, a la cual se le aplican los principios de inferencia estadística para responder, si efectivamente el promedio de ingresos en las ciudades capitales es mayor a la del resto de ciudades.\n\nDe manera muy sencilla, lo que se hace es utilizar algunas propiedades de la teoría estadística, para determinar bajo cierto nivel de confianza (que puede ser entendido como *'bajo cierta probabilidad'*) cual es el verdadero valor de una medida (Ej. El promedio de ingreso en Bogotá) a partir de un subconjunto de la totalidad de los datos.\n\nHacer inferencia estadística me permite no solo conocer una medida particular sobre cierta unidad de observación, sino también tener mayor certeza y rigurosidad estadística sobre la comparación entre unidades de observación (Ej.: el promedio de ingresos de Bogotá es significativamente superior al de Cali).\n\nDetrás de esto hay intervalos de confianza, pruebas de hipótesis y teorías sobre la distribución de los datos que requerirían más de tres horas de clase, por ello nos centraremos en intervalos de confianza (con los cuales se pueden realizar pruebas de hipótesis) y en los comandos para hacer pruebas de hipótesis sin revisar con tanto detalle la teoría estadística subyacente, si la requieren un buen material de apoyo con ejemplos en R está disponible en [Introduction to Statistics and Data Analysis](https://www.filepicker.io/api/file/TgilBNiCSk26axWSRDVA).\n\n## Intervalos de confianza\n\nEn el módulo 2 cuando hicimos análisis univariado, calculamos la media de alguna variable continua, ese cálculo es lo que se conoce como estimación puntual, la información que obtenemos de ella, solo se corresponde con los datos disponibles.\\\nUn mayor grado de información lo podemos obtener calculando los intervalos de confianza, partiendo de que la estimación puntual es obtenida de una muestra y que nuestro interés es el valor poblacional (no muestral), podemos calcular un límite inferior y un límite superior entre cuyos valores se encuentra, bajo cierto nivel de confianza ($95\\%$ generalmente) el parámetro poblacional.\n\nVeámoslo con un ejemplo, la **Encuesta Nacional de Ocupación y Empleo - ENOE** es un proyecto estadístico realizado por el INEGI trimestralmente en México y del cual se obtienen medidas estadísticas que pueden ser de interés, por ejemplo, el promedio de ingresos por Estados Federales, hagamos ese cálculo y posteriormente añadámosle los intervalos de confianza.\n\nLa base a utilizar es **\"ENOE_SDEMT224.dta\"** la cual corresponde al cuestionario sociodemográfico del segundo trimestre de 2024.\n\n### Paso 1: Obtener la estimación puntual\n\nLo primero que debemos hacer es obtener la estimación puntual del ingreso para cada estado, eso lo hacemos utilizando las funciones `group_by()` y `summarise()`. Además del promedio, vamos a obtener el desvió estándar del ingreso por entidad y el tamaño de la muestra por entidad.\n\n::: {.callout-note appearance=\"simple\"}\nPara los cálculos, vamos a tener en cuenta solamente a aquellas personas cuyo ingreso es mayor a 0, por lo tanto debemos agregar un filtro que garantice está condición\n\n`base %>% filter(inocup > 0)`\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls()) # Limpieza del ambiente de trabajo\n\nlibrary(tidyverse) # Activación de librería\n\nbase <- haven::read_dta(file = \"bases/ENOE_SDEMT224.dta\") # Carga de la base de datos\n\n# la variable 'ent' corresponte al Estado y la variable 'ingocup' al\n# ingreso mensual\n\n# calculo de la media, el desvio estandar del ingreso y el tamaño de muestra por estado\n\nmediasEnt <- base %>% \n  filter(ingocup > 0) %>% \n  group_by(ent) %>% \n  summarise(mediaIngreso = mean(ingocup),\n            desvioIngreso = sd(ingocup),\n            tamanio = n())\n\nmediasEnt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 32 × 4\n   ent                       mediaIngreso desvioIngreso tamanio\n   <dbl+lbl>                        <dbl>         <dbl>   <int>\n 1  1 [Aguascalientes]              9309.         6221.    2821\n 2  2 [Baja California]            13342.         9001.    4047\n 3  3 [Baja California Sur]        13593.        11182.    3491\n 4  4 [Campeche]                   10515.        10219.    6465\n 5  5 [Coahuila de Zaragoza]       11388.         8666.    6262\n 6  6 [Colima]                     10409.         7618.    3416\n 7  7 [Chiapas]                     8111.         6966.    6511\n 8  8 [Chihuahua]                  12057.         8571.    4904\n 9  9 [Ciudad de México]           12095.        13734.    2276\n10 10 [Durango]                     9150.         6717.    5016\n# ℹ 22 more rows\n```\n\n\n:::\n:::\n\n\nLa variable `ent` es un código que se corresponde con cada uno de los 32 estados federativos de los Estados Unidos Mexicanos, tanto si eres mexicano o no, es más cómodo ver los nombres de los estados y no esos números.\\\nDado que la base es un archivo \".dta\", en la variable `ent` esta almacenado el nombre del estado al que corresponde el código. Incorporemos los nombres como una variable más.\\\nPodemos hacerlo creando una nueva variable (para ello debemos asegurarnos que el orden den vector con los nombres) coincide con el orden de las filas de `mediasEnt`; la otra alternativa es hacer un Join de bases, en este caso no hace falta revisar el orden de las filas y del vector.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creo una base de datos que contenga la etiqueta y los nombres\n\nnumeroEstado <- attr(mediasEnt$ent, which = \"labels\")\nnombreEstado <- names(attr(mediasEnt$ent, which = \"labels\"))\n\nestados <- tibble(etiqueta = numeroEstado,\n                  nombre = nombreEstado)\n\n# Pego los nombres a la base 'estados' a la base 'mediasEnt' a partir de la funcion left_join()\n\nmediasEnt <- mediasEnt %>% \n  left_join(y = estados,\n            by = c(\"ent\" = \"etiqueta\")) %>% \n  relocate(nombre, .after = ent) %>%        # con relocate puedo modificar la posición de la variable\n  arrange(desc(mediaIngreso))               # organizo los datos de mayor a menor media de ingreso\n\n# Veo el resultado\n\nprint(mediasEnt, n = 32)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 32 × 5\n   ent                                 nombre mediaIngreso desvioIngreso tamanio\n   <dbl+lbl>                           <chr>         <dbl>         <dbl>   <int>\n 1  3 [Baja California Sur]            Baja …       13593.        11182.    3491\n 2  2 [Baja California]                Baja …       13342.         9001.    4047\n 3 19 [Nuevo León]                     Nuevo…       12379.        10223.    4813\n 4  9 [Ciudad de México]               Ciuda…       12095.        13734.    2276\n 5  8 [Chihuahua]                      Chihu…       12057.         8571.    4904\n 6  5 [Coahuila de Zaragoza]           Coahu…       11388.         8666.    6262\n 7 25 [Sinaloa]                        Sinal…       11370.         9456.    4210\n 8 23 [Quintana Roo]                   Quint…       10856.         7743.    3498\n 9 26 [Sonora]                         Sonora       10703.         7422.    3616\n10 28 [Tamaulipas]                     Tamau…       10515.         7561.    5571\n11  4 [Campeche]                       Campe…       10515.        10219.    6465\n12  6 [Colima]                         Colima       10409.         7618.    3416\n13 14 [Jalisco]                        Jalis…       10237.         6524.    3803\n14 22 [Querétaro]                      Queré…       10188.         8477.    2003\n15 18 [Nayarit]                        Nayar…        9994.         8075.    5114\n16 24 [San Luis Potosí]                San L…        9947.         8373.    3357\n17 27 [Tabasco]                        Tabas…        9414.         8758.    4053\n18  1 [Aguascalientes]                 Aguas…        9309.         6221.    2821\n19 16 [Michoacán de Ocampo]            Micho…        9307.         7480.    4173\n20 31 [Yucatán]                        Yucat…        9299.         8138.    4646\n21 10 [Durango]                        Duran…        9150.         6717.    5016\n22 32 [Zacatecas]                      Zacat…        8967.         6631.    3349\n23 30 [Veracruz de Ignacio de la Llav… Verac…        8844.         8132.    5354\n24 11 [Guanajuato]                     Guana…        8830.         6231.    4442\n25 13 [Hidalgo]                        Hidal…        8815.         7181.    3379\n26 15 [México]                         México        8564.         7258.    4072\n27  7 [Chiapas]                        Chiap…        8111.         6966.    6511\n28 20 [Oaxaca]                         Oaxaca        8062.         6633.    3762\n29 12 [Guerrero]                       Guerr…        7986.         6661.    3695\n30 21 [Puebla]                         Puebla        7942.         6564.    4398\n31 29 [Tlaxcala]                       Tlaxc…        7498.         6811.    4045\n32 17 [Morelos]                        Morel…        7133.         4631.    1719\n```\n\n\n:::\n:::\n\n\n### Paso 2: Calcular el Margen\n\nPara calcular el intervalo de confianza, matemáticamente lo que debemos hacer es bastante simple. Tomar la media para cada estado, que podemos simbolizar con $\\bar{X}_i$, restarle un valor para el límite inferior ($L_{i}$) y sumarle un valor para el límite superior ($L_{s}$). Además, el valor que sumamos es igual al valor que restamos.\\\n\n¿Qué valor sumar y restar?\\\nEste valor depende fundamentalmente de tres cosas:\n\n- El tamaño de la muestra `n` (el cual obtuvimos en la tabla inicial).\n- La distribución de los datos, es decir, que tan dispersos con respecto a la media se encuentran las observaciones.\n- El que la varianza poblacional sea conocida o no (en general es no conocida).\n- El nivel de significancia $\\alpha$ (o el nivel de confianza con el que decidamos trabajar).\n\nllamaremos a ese valor **Margen** y se obtiene de la siguiente forma\n\n- Con varianza poblacional conocida $(\\sigma^2)$\n\n  - Se utiliza la distribución normal estándar.\n  - Margen = $Z_{\\frac{\\alpha}{2}}\\cdot\\frac{\\sigma}{\\sqrt{n}}$\n  - Sintaxis R: `abs(qnorm(p = 0.025))*(desvío/(n)^(1/2))`\n\n- Con varianza poblacional desconocida $(S^2)$\n\n  - Se utiliza la distribución t-Student.\\\n  - Margen = $t_{(\\frac{\\alpha}{2}, n-1)}\\cdot\\frac{S}{\\sqrt{n}}$\n  - Sintaxis R: `abs(qt(p = 0.025, df = (n-1)))*(desvío/(n)^(1/2))`\n\nObtengamos el margen a sumar y restar para obtener los límites del intervalo de confianza del promedio de ingresos en cada estado.\\\nPara ello debemos utilizar la fórmula para varianza poblacional desconocida, y lo haremos con un nivel de confianza del $95\\%$.\\\nOperacionalmente añadiremos variables a la base `mediasEnt`, lo cual nos permitirá más adelante calcular la amplitud de los intervalos y graficarlos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmediasEnt <- mediasEnt %>% \n  mutate(cuantil95 = abs(qt(p = 0.025, df = tamanio-1)),\n         margen = cuantil95*desvioIngreso/sqrt(tamanio))\n\nmediasEnt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 32 × 7\n   ent                nombre mediaIngreso desvioIngreso tamanio cuantil95 margen\n   <dbl+lbl>          <chr>         <dbl>         <dbl>   <int>     <dbl>  <dbl>\n 1  3 [Baja Californ… Baja …       13593.        11182.    3491      1.96   371.\n 2  2 [Baja Californ… Baja …       13342.         9001.    4047      1.96   277.\n 3 19 [Nuevo León]    Nuevo…       12379.        10223.    4813      1.96   289.\n 4  9 [Ciudad de Méx… Ciuda…       12095.        13734.    2276      1.96   565.\n 5  8 [Chihuahua]     Chihu…       12057.         8571.    4904      1.96   240.\n 6  5 [Coahuila de Z… Coahu…       11388.         8666.    6262      1.96   215.\n 7 25 [Sinaloa]       Sinal…       11370.         9456.    4210      1.96   286.\n 8 23 [Quintana Roo]  Quint…       10856.         7743.    3498      1.96   257.\n 9 26 [Sonora]        Sonora       10703.         7422.    3616      1.96   242.\n10 28 [Tamaulipas]    Tamau…       10515.         7561.    5571      1.96   199.\n# ℹ 22 more rows\n```\n\n\n:::\n:::\n\n\n### Paso 3: Calcular los intervalos de confianza\n\nYa obtenido el margen (el valor a sumar y restar) para calcular el límite inferior y superior del intervalo, solo queda calcularlos.\\\nAñadamos dos variables a nuestra base `mediasEnt`, una con el límite inferior (con nombre Li) y otra con el límite superior (con nombre Ls).\\\nAlgo que suele interesar es la amplitud del intervalo (la distancia entre el límite superior e inferior), entre menos amplio sea, más precisa es la información que estamos obteniendo sobe el valor del parámetro, incluyamos este cálculo en la base `mediasEnt`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmediasEnt <- mediasEnt %>% \n  mutate(Li = mediaIngreso - margen,\n         Ls = mediaIngreso + margen,\n         amplitud = Ls - Li)\n\nprint(mediasEnt %>% \n  select(nombre, mediaIngreso, Li, Ls, amplitud), n = 32)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 32 × 5\n   nombre                          mediaIngreso     Li     Ls amplitud\n   <chr>                                  <dbl>  <dbl>  <dbl>    <dbl>\n 1 Baja California Sur                   13593. 13222. 13964.     742.\n 2 Baja California                       13342. 13064. 13619.     555.\n 3 Nuevo León                            12379. 12091. 12668.     578.\n 4 Ciudad de México                      12095. 11530. 12660.    1129.\n 5 Chihuahua                             12057. 11817. 12297.     480.\n 6 Coahuila de Zaragoza                  11388. 11173. 11603.     429.\n 7 Sinaloa                               11370. 11084. 11656.     571.\n 8 Quintana Roo                          10856. 10600. 11113.     513.\n 9 Sonora                                10703. 10461. 10945.     484.\n10 Tamaulipas                            10515. 10317. 10714.     397.\n11 Campeche                              10515. 10266. 10764.     498.\n12 Colima                                10409. 10154. 10665.     511.\n13 Jalisco                               10237. 10030. 10445.     415.\n14 Querétaro                             10188.  9817. 10560.     743.\n15 Nayarit                                9994.  9773. 10215.     443.\n16 San Luis Potosí                        9947.  9664. 10230.     567.\n17 Tabasco                                9414.  9144.  9683.     539.\n18 Aguascalientes                         9309.  9079.  9538.     459.\n19 Michoacán de Ocampo                    9307.  9080.  9534.     454.\n20 Yucatán                                9299.  9065.  9533.     468.\n21 Durango                                9150.  8964.  9335.     372.\n22 Zacatecas                              8967.  8743.  9192.     449.\n23 Veracruz de Ignacio de la Llave        8844.  8626.  9062.     436.\n24 Guanajuato                             8830.  8647.  9013.     367.\n25 Hidalgo                                8815.  8573.  9057.     484.\n26 México                                 8564.  8341.  8787.     446.\n27 Chiapas                                8111.  7942.  8280.     338.\n28 Oaxaca                                 8062.  7850.  8274.     424.\n29 Guerrero                               7986.  7771.  8201.     430.\n30 Puebla                                 7942.  7748.  8136.     388.\n31 Tlaxcala                               7498.  7288.  7708.     420.\n32 Morelos                                7133.  6914.  7352.     438.\n```\n\n\n:::\n:::\n\n\n### Paso 4: Gráfico de los intervalos\n\nYa los intervalos de confianza de la media de ingreso para cada estado están calculados, una manera de presentarlos es en la tabla que acabamos de mostrar, de ella podemos decir que en el segundo trimestre de 2024, el ingreso promedio en Ciudad de México estaba entre los 11530.48 y 12659.54 pesos mexicanos con un nivel del confianza del $95\\%$, eso es mucho mejor que decir que el pomedio de ingreso en Ciudad de México fue de 12095.01, al menos para quienes valoran la información.\n\nSin embargo, una mejor manera de presentar estos resultados es a partir de un gráfico que me permita hacer la comparación entre estados, el código es relativamente sencillo con **{ggplot2}**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grafico de intervalos de confianza de ingreso promedio por estado\n\nmediasEnt %>% \n  ggplot(mapping = aes(x = mediaIngreso, y = reorder(nombre, desc(mediaIngreso)))) +\n  geom_point() +\n  geom_errorbar(mapping = aes(xmin = Li, xmax = Ls)) +\n  labs(title = \"Media de ingreso mensual por entidades federativas en México\",\n       subtitle = \"Los datos corresponden al 2 trimestre de 2024\",\n       y = NULL,\n       x = \"Pesos Mexicanos\",\n       caption = \"Fuente: elaboración propia en base a ENOE-INEGI 2024\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### ¿Qué información adicional me ofrecen los intervalos de confianza?\n\nAl inicio se mencionó algo respecto a la prueba de hipótesis subyacente a los intervalos de confianza, el razonamiento es muy sencillo, si no existen solapamientos entre los intervalos de confianza de dos unidades de observación, podemos afirmar que las medias de esas dos unidades de observación, son significativamente diferentes, caso contrario, no puedo afirmar que las medias sean significativamente distintas. Esto no reemplaza la prueba de hipótesis y en casos en que los intervalos de confianza estén muy cerca deberiamos realizar un `t.test()`.\\\nUtilizando la información que acabamos de calcular, podemos afirmar que no existen diferencias significativas en el ingreso promedio entre Ciudad de México y Chihuahua, pero si entre Ciudad de México y Baja California.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmediasEnt %>% \n  filter(nombre %in% c(\"Baja California\",\n                       \"Ciudad de México\",\n                       \"Chihuahua\")) %>% \n  ggplot(mapping = aes(x = mediaIngreso, y = reorder(nombre, desc(mediaIngreso)))) +\n  geom_point() +\n  geom_errorbar(mapping = aes(xmin = Li, xmax = Ls)) +\n  labs(title = \"Prueba de diferencia de medias a partir de los Intervalos de Confianza\\n\",\n       subtitle = \"Dado que se solapan los intervalos de CDMX y Chihuahua, no existen diferencias\\nsignificativas en el ingreso promedio mensual de estas dos entidades.\\n\\nMientras que Baja California muestra un ingreso promedio mensual significativamente\\nsuperior a CDMX\",\n       y = NULL,\n       x = \"Pesos Mexicanos\",\n       caption = \"Fuente: elaboración propia en base a ENOE-INEGI 2024\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Prueba de hipótesis de diferencia de medias\n\nYa nos aproximamos a la prueba de diferencia de medias, pero vale la pena abordarla de manera más completa debido a que es muy utilizada para sostener argumentos y en algunas ocasiones, es evidencia suficiente para una tesis o establecer un efecto causal.\\\nNos interesa saber si dada una condición o tratamiento sobre ciertas unidades de observación, se genera una diferencia significativa en el valor de una variable cuantitativa observada. El ejemplo de ingresos es un buen ejemplo y podemos tomar como condición de tratamiento el sexo.\n\nPara poder determinar si en México las mujeres tienen un ingreso significativamente diferente al de los hombres, debemos realizar una prueba de hipótesis que verifique si para cierto nivel de confianza esas medias son significativamente diferentes o no.\n\nFormalmente, para realizar una prueba de hipótesis de diferencia de medias, debemos definir un nivel de confianza y plantear nuestra prueba de hipótesis en términos de hipótesis nula e hipótesis alternativa.\\\nEn general y por principio espistemológico de cómo hacemos ciencia, lo que buscamos al utilizar nuestros datos es falsar la hipótesis nula (principio popperiano de falsación), en el ejemplo puntual planteado aquí, hay argumentos económicos y sociales que sostienen que las mujeres enfrentan una discriminación en el ingreso, por lo que *a priori* esperaríamos que el ingreso de las mujeres sea menor que el de los hombres o al menos diferente, esa sería nuestra hipótesis alternativa (lo que esperamos encontrar), nuestra hipótesis nula sería que las mujeres tienen un ingreso mayor o igual al de los hombres (buscamos falsar esta aseveración).\n\nEn el caso concreto de diferencia de ingresos por género, siendo $\\bar{X}_M$ la media de ingresos de mujeres y $\\bar{X}_H$ la media de ingresos de hombres, nuestras hipótesis nula ($H_0$) y alternativa ($H_1$) son:\n\n$$H_0: \\bar{X}_M = \\bar{X}_H$$ $$H_1: \\bar{X}_M \\neq \\bar{X}_H$$\n\nEsta hipótesis se conoce como prueba de dos colas, porque solo se afirma que son distintas, no se afirma nada respecto a si una de las medias es mayor o menor que la otra.\n\nComo criterios de decisión respecto a la prueba, tenemos el intervalo de confianza de la diferencia de medias, el p-valor y el valor crítico, todos estos criterios son devueltos por la función `t.test()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\npruebaMedias <- t.test(formula = ingocup ~ sex,        # En el argumento formula va 'var_cuanti' ~ 'var_categorica'\n                       data = base %>%                 # En data pongo la base de datos que contiene las variables\n                              filter(ingocup > 0))             \n\n# La variable 'sex' esta codificada de la forma:\n# 1 = Hombre\n# 2 = Mujer\n\npruebaMedias\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  ingocup by sex\nt = 60.001, df = 131719, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0\n95 percent confidence interval:\n 2537.912 2709.317\nsample estimates:\nmean in group 1 mean in group 2 \n      11038.189        8414.574 \n```\n\n\n:::\n:::\n\n\nLa salida del `t.test()` es similar a la salida de la regresión, centrémonos en tres cosas, el *P-Valor*, el Valor del test estadístico *t-Student* y los *intervalos de confianza*.\n\n- **P-Valor:** Lo encontramos en la parte superior derecha, dado que es menor que el nivel de significancia de 0.05, podemos afirmar que la media de ingreso entre hombres y mujeres es diferente a un nivel de confianza del $95\\%$\n- **Valor del test estadístico 't':** Lo encontramos en la parte superior izquierda, este valor debe compararse con un valor teórico de la distribución t-Student, el cual depende del nivel de confianza y del número de observaciones, en general, valores mayores a 2 implican el rechazo de la hipótesis nula cuando la hipótesis es de igualdad de medias, en este caso el valor de 60 es muy superior a 2, por lo que podemos afirmar por este criterio que las medias de ingreso entre hombres y mujeres son diferentes.\n- **Intervalos de confianza:** Aparecen como *'95 percent confidence interval'*, lo que nos muestran es el intervalo de confianza de la diferencia (de la resta) entre la media de ingreso de hombres y la media de ingreso de mujeres. Dado que los intervalos no contienen el cero (tienen el mismo signo, ambos positivos), podemos afirmar que la media de ingresos entre hombres y mujeres es diferente, además, el ingreso de los hombres es superior al de las mujeres.\n\nAlgo que resulta evidente de los tres criterios anteriores, es que todos coinciden, lo cual debería ayudarme en situaciones donde la interpretación es algo más compleja, si rechazo la hipótesis nula por el criterio de intervalos de confianza, la tengo que rechazar también por criterio de p-valor o por criterio de valor crítico.\n\nA continuación se muestra el gráfico de los intervalos de confianza de la diferencia de medias, lo relevante del mismo es mostrar la distancia del intervalo respecto al cero, pues esto demuestra que la diferencia es significativa al nivel de confianza elegido.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npruebaMedias <- t.test(formula = ingocup ~ sex,\n                 data = base)\n\ndf <- tibble(dif = pruebaMedias$estimate[1] - pruebaMedias$estimate[2],\n             Li = pruebaMedias$conf.int[1],\n             Ls = pruebaMedias$conf.int[2])\n\ndf %>% \n  ggplot(mapping = aes(x = \"Diferencia de Medias Ingreso_Hombre - Ingreso_Mujer\", \n                       y = dif)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = Li, ymax = Ls), width = 0.4) +\n  geom_hline(mapping = aes(yintercept = 0),\n             linetype = \"dashed\",\n             color = \"red\") +\n  labs(title = \"Intervalo de confianza de la diferencia de medias de ingreso por sexo\\nIngreso Hombres - Ingreso Mujeres\",\n       x = NULL,\n       y = \"Pesos Mexicanos\") +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nLo que podemos concluir del test de diferencia de medias, es que efectivamente la diferencia en el promedio de ingresos entre hombres y mujeres es significativa, los hombres ganan entre 2007 y 2086.6 pesos más que las mujeres.\n\n## Prueba de hipótesis de diferencia de proporciones\n\nLa prueba de diferencia de proporciones es otro test estadístico muy utilizado en ciencias sociales, la lógica subyacente es muy similar a la de diferencia de medias, sin embargo, por cuestiones relativas a la teoría estadística, en lugar de utilizar la distribución t-Student se utiliza la distribución normal.\\\nRespecto a la selección del nivel de confianza, de los criterios para determinar el resultado del test o del planteamiento de hipótesis nula y alternativa, no hay cambios relevantes.\n\nPara ver cómo hacer una prueba de diferencia de proporciones, utilicemos la variable **'sub_o'**, la cual toma el valor de 1 si el individuo se considera subocupado y el de 0 si el individuo no se encuentra subocupado.\\\nHagamos la comparación entre las entidades de Chihuahua y Ciudad de México, las cuales muestran niveles de ingreso mensual parecidos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npruebaProp <- base %>% \n  filter(ent %in% c(9, 8)) %>% \n  group_by(ent, sub_o) %>% \n  summarise(frecAbs = n())\n\npruebaProp <- pruebaProp %>% \n  ungroup() %>% \n  group_by(ent) %>% \n  mutate(total = sum(frecAbs)) %>% \n  ungroup() %>% \n  mutate(frecRel = frecAbs/total)\n\npruebaProp <- pruebaProp %>% \n  filter(sub_o != 0)\n\npruebaProp <- pruebaProp %>% \n  left_join(y = estados,\n            by = c(\"ent\" = \"etiqueta\"))\n\n# Tabla con las proprciones a comparar\n\npruebaProp %>% \n  select(nombre, frecAbs, total, frecRel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  nombre           frecAbs total frecRel\n  <chr>              <int> <int>   <dbl>\n1 Chihuahua            355 15449  0.0230\n2 Ciudad de México     491  9652  0.0509\n```\n\n\n:::\n\n```{.r .cell-code}\n# Función para realizar la diferencia de proporciones\n\nprop.test(x = pruebaProp$frecAbs, n = pruebaProp$total)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  pruebaProp$frecAbs out of pruebaProp$total\nX-squared = 141.04, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.03295545 -0.02282745\nsample estimates:\n    prop 1     prop 2 \n0.02297883 0.05087029 \n```\n\n\n:::\n:::\n\n\nEn los valores de la tabla se observan diferencias importantes, mientras en Ciudad de México hay un $5\\%$ de población subocupada, en Chihuahua ese valor es del $2.2\\%$.\\\nEso ya me permite intuir que la diferencia en las proporciones es estadísticamente significativa, lo que se comprueba al realizar el `prop.test()`.\n\nLo que pide la función para realizar el test, son las frecuencias absolutas y el total de observaciones de cada una de las unidades a comparar, en este caso Ciudad de México tiene 9652 personas encuestadas, mientras Chihuahua tiene 15449.\n\nUna vez obtenidos los resultados, la lectura es similar al de diferencia de medias, el P-Valor menor al 0.05 indica que la diferencia de proporciones es significativa al $95\\%$ de confianza, el valor critico *X-squared* es muy alto, lo que me conduce a rechazar la hipótesis nula de que las proporciones son iguales, finalmente, lo intervalos de confianza no contienen el cero, dando cuenta de que la diferencia es significativa, teniendo CDMX una proporción de subocupados superior a la de Chihuahua.\n\n## Prueba ANOVA (ANalysis Of VAriance)\n\nDe la misma familia de la diferencia de medias, viene la prueba ANOVA, ¿Que me aporta la prueba ANOVA respecto a la prueba de diferencia de medias?, la prueba de diferencia de medias solo me permite comparar dos poblaciones, mientras que la prueba ANOVA me permite comparar más de dos.\\\nAhora bien, si se llama análisis de varianza, porque sirve para comparar medias, porque verifica si existen diferencias significativas en las medias a partir de la dispersión de los datos.\n\nUn ejemplo gráfico puede ayudar, el siguiente gráfico es a partir de datos simulados, en el gráfico de la izquierda hay una dispersión entre grupos mucho mayor a la dispersión adentro de cada grupo, pasa lo contrario con el gráfico de la derecha.\\\nEsto indicaría que la diferencia de medias en los grupos de la izquierda es significativa, mientras la diferencia de medias en los grupos de la derecha no es tan evidente.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nUtilicemos la prueba ANOVA para ver las diferencias en el ingreso según el máximo nivel educativo alcanzado, para aplicarla debemos utilizar los comandos vistos en el análisis de regresión simple (en el fondo la prueba ANOVA es una regresión siendo la variable 'X' una variable categórica de al menos dos niveles).\\\n\nLa variable `cs_p_13` contiene la información sobre máximo nivel educativo alcanzado, desde ninguna educación formal hasta doctorado, convirtamos esta variable en categórica y apliquemos la prueba ANOVA.\n\nLo primero es filtrar los NA y los casos '99', que corresponden a datos no disponibles, para ser coherentes con los análisis anteriores, nos quedamos solo con las observaciones cuyo ingreso es mayor a 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova <- base %>% \n  filter(!is.na(cs_p13_1) & cs_p13_1 != 99 & ingocup > 0)\n\nnombresEdu <- names(attr(anova$cs_p13_1, which = \"labels\"))\n\nanova$educacion <- factor(case_when(\n  anova$cs_p13_1 == 0 ~ nombresEdu[1],\n  anova$cs_p13_1 == 1 ~ nombresEdu[2],\n  anova$cs_p13_1 == 2 ~ nombresEdu[3],\n  anova$cs_p13_1 == 3 ~ nombresEdu[4],\n  anova$cs_p13_1 == 4 ~ nombresEdu[5],\n  anova$cs_p13_1 == 5 ~ nombresEdu[6],\n  anova$cs_p13_1 == 6 ~ nombresEdu[7],\n  anova$cs_p13_1 == 7 ~ nombresEdu[8],\n  anova$cs_p13_1 == 8 ~ nombresEdu[9],\n  anova$cs_p13_1 == 9 ~ nombresEdu[10]), \n  levels = nombresEdu[1:10])\n\nregAnova <- lm(formula = ingocup ~ educacion,\n               data = anova)\n\nsummary(regAnova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ingocup ~ educacion, data = anova)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-22901  -4116   -897   2303 198304 \n\nCoefficients:\n                                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                            5623.6      139.1  40.433   <2e-16 ***\neducacionPreescolar                    1511.0      999.3   1.512    0.131    \neducacionPrimaria                      1600.3      148.5  10.777   <2e-16 ***\neducacionSecundaria                    2792.6      144.5  19.320   <2e-16 ***\neducacionPreparatoria o bachillerato   3829.4      145.7  26.278   <2e-16 ***\neducacionNormal                        5586.6      646.2   8.645   <2e-16 ***\neducacionCarrera técnica               4641.4      185.4  25.031   <2e-16 ***\neducacionProfesional                   8073.1      146.1  55.249   <2e-16 ***\neducacionMaestría                     15072.8      206.9  72.867   <2e-16 ***\neducacionDoctorado                    17877.3      413.9  43.189   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7729 on 132189 degrees of freedom\nMultiple R-squared:  0.1228,\tAdjusted R-squared:  0.1228 \nF-statistic:  2056 on 9 and 132189 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nLa interpretación de la salida es un poco compleja, lo que nos muestra cada uno de los coeficientes es en cuanto se incrementaría en promedio alcanzar ese nivel especifico de educación, respecto a una categoría de referencia que en este caso es no tener educación formal.\\\nEn general se observa que a mayores niveles de educación mayor es el incremento en el ingreso promedio, se observan tres niveles relevantes. En primer lugar, terminar la secundaria, el bachillerato o tener una carrera técnica, hace que el ingreso promedio se incremente entre $\\$2,792.6$ y $\\$4,641.4$ pesos mexicanos. En segundo lugar, ser profesional hace que el ingreso promedio se incremente $\\$8,073.1$ pesos mexicanos. Por último, tener maestría o doctorado, hace que los ingresos se incrementen entre $\\$15,072.8$ y $\\$17,877.3$ pesos mexicanos.\n\n¿Como saber si las diferencias entre grupos son significativas? de nuevo aparecen los intervalos de confianza, de allí la utilidad de saberlos calcular, nos permite hacer pruebas de hipótesis entre grupos sin necesidad de abordar toda la teoría estadística subyacente a una prueba más compleja como la prueba ANOVA.\n\nCalculemos los intervalos de confianza del ingreso medio por nivel educativo alcanzado y verifiquemos en qué casos existen diferencias significativas y en qué casos no.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmediaEduc <- anova %>%\n  group_by(educacion) %>%   \n  summarise(mediaIngreso = mean(ingocup),\n            desvioIngreso = sd(ingocup),\n            tamanio = n(),\n            cuantil95 = abs(qt(p = 0.025, df = tamanio-1)),\n            margen = cuantil95*desvioIngreso/sqrt(tamanio),\n            Li = mediaIngreso - margen,\n            Ls = mediaIngreso + margen)\n  \n\nmediaEduc %>% \n  ggplot(mapping = aes(x = educacion, y = mediaIngreso)) +\n  geom_point() +\n  geom_errorbar(mapping = aes(ymin = Li, ymax = Ls)) +\n  theme(axis.text.x = element_text(angle = 90))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nLas conclusiones a partir de este gráfico de intervalos de confianza de las medias son similares a los de la regresión de la prueba ANOVA, hay un primer salto si se terminó el bachillerato, la secundaria o se tiene una carrera técnica. Un segundo salto si se es profesional y un tercer salto si se tiene maestría o doctorado. Además, para quienes actualmente están realizando una maestría y tienen dudas respecto al doctorado, el gráfico nos muestra que la diferencia de ingresos es significativa a un nivel de confianza del $95\\%$, un aliciente económico para decidir estudiar 4 o 5 años más, debido a su efecto sobre el ingreso medio.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}