{
  "hash": "360f5812c4878a076d51ae7a428afd0d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Módulo 3: Análisis estadístico bivariado\"\nauthor: \"Gerardo Esteban, Gómez-Santiago\"\ntoc: true\nformat: \n  html:\n    code-links:\n      - text: Video YouTube\n        icon: camera-reels\n        href: https://youtu.be/T-JHMBjzt4U\n      - text: Repositorio GitHub\n        icon: file-code\n        href: https://github.com/GomezGerardoEsteban/Tidyverso/tree/main/TallerR/Modulo3\n    mathjax: default\n    code-tools: true\n    self-contained: true\nexecute:\n  warning: false\nimage: \"modulo3.png\"\n---\n\n## Introducción\n\nLa principal razón por la que utilizamos la estadística como herramienta de investigación, es porque nos permite generar evidencia empírica sobre la relación entre dos o más variables.\\\nPor ejemplo, teóricamente podemos asumir que el desarrollo económico tiene una relación positiva con la tolerancia política o los valores democráticos de un país. En el fondo, establecemos esa relación porque tenemos un argumento teórico que lo justifica.\\\nEn el caso del desarrollo económico y los valores democráticos, podemos argumentar que a mayor desarrollo económico, mayor es el costo para los ciudadanos de enfrentar un gobierno dictatorial que pone en tela de juicio los derechos de propiedad, pues los ciudadanos tienen aversión a la perdida y no quieren perder sus posesiones, lo cual es más probable que suceda bajo dictaduras.\n\nLograr justificar estadísticamente un argumento causal es algo que excede este curso y que en el mundo de la estadística se conoce como **inferencia causal**, lo que si podemos evidenciar con estadística descriptiva, es si efectivamente el desarrollo económico, medido por el PIB per cápita, tiene una relación positiva con los valores democráticos, medidos por la tasa de participación en elecciones (por ejemplo).\\\n\n::: {.callout-note appearance=\"simple\"}\nA partir de estadística descriptiva, no podemos garantizar que la causa de una relación planteada se debe a nuestro planteamiento teórico, pero si podemos dar cuenta de que la relación existe.\n:::\n\nEn el ejemplo hipotético que planteamos, estamos tratando a dos variables continuas, el **PIB per cápita**, el cual esta medido en unidades monetarias y la **tasa de participación en elecciones**, la cual es un porcentaje con valores posibles entre cero y cien.\\\nEn general, las variables cuantitativas son las más susceptibles al análisis bivariado, a las cuales se les calcula covarianza, correlación y con las que generalmente se realizan regresiones.\n\nSin embargo no son las únicas, es posible verificar si existe relación entre variables categóricas.\\\nPor ejemplo, nos interesa saber si fumar o no fumar (variable categórica de dos niveles) tiene relación con tener o no tener cáncer de pulmón (variable categórica de dos niveles), para ello se genera una prueba estadística conocida como prueba de independencia chi-cuadrado, la cual nos indica si las variables son independientes o no.\n\nNo haremos un análisis exhaustivo de la estadística subyacente a las medidas mencionadas, nos enfocaremos en la obtención de los valores a través de R y RStudio y en su interpretación.\n\n## Covarianzas\n\nPodemos rastrear el origen del análisis bivariado en el análisis univariado, a lo largo del módulo anterior, se hizo énfasis en la necesidad de obtener medidas de posición y de dispersión para conocer la distribución de los datos.\\\nComo medidas de dispersión tenemos fundamentalmente la varianza y la desviación estándar, que en el fondo son la misma medida, debido a que la desviación estándar es una transformación de la varianza ($Desvio =  \\sqrt{Varianza}$).\n\nSi revisamos la fórmula matemática de la varianza, vemos que es la suma de las diferencias de cada observación con respecto a la media elevadas al cuadrado. Formalmente podemos expresarlo como:\n\n$$\\sigma^2 = \\frac{\\sum_{i = 1}^n (x_i - \\bar{x})^2}{n-1} = \\frac{1}{n-1} \\cdot \\sum_{i = 1}^n (x_i - \\bar{x})\\cdot(x_i - \\bar{x})$$ donde $\\bar{x}$ simboliza el promedio de $x$, $n$ el número de observaciones y $x_i$ los sucesivos valores de $x$.\n\n### ¿Qué es lo que cambia en la varianza para poder obtener la covarianza?\n\nQue en lugar de trabajar con una sola variable trabajamos con dos, tomando la última expresión de la fórmula matemática anterior, vemos que se repite $(x_i - \\bar{x})$. En la covarianza, lo que hacemos es cambiar uno de estos términos por su equivalente en la segunda variable de interés, llamemos esa segunda variable de interés $y$. La fórmula de la covarianza es:\n\n$$cov_{(x,y)} = \\frac{\\sum_{i = 1}^n (x_i - \\bar{x})\\cdot(y_i - \\bar{y})}{n-1}$$\n\ndonde $\\bar{y}$ es el promedio de la variable $y$ y $y_i$ son los sucesivos valores de $y$ (el resto de símbolos son los mismos que se explicaron en la expresión de la varianza).\n\nLa estructura en la fórmula de la covarianza es casi idéntica a la fórmula de la varianza, solo que en lugar de trabajar sobre una variable ($X$), ahora trabajamos sobre dos variables ($X,Y$).\n\n### ¿Qué es lo que aporta la Covarianza?\n\nLa covarianza me permite conocer **cual es el sentido del cambio** (positivo o negativo) en una variable $(X)$ ante cambios en otra variable $(y)$, es decir, si $x$ y $y$ tienen una relación positiva o negativa.\\\nLo de *\"el sentido del cambio\"* es relevante, porque la covarianza no me permite saber a ciencia cierta si la relación entre $x$ y $y$ es fuerte o débil, solo si esa relación es positiva o negativa.\n\nVeamos el ejemplo entre desarrollo económico (medida por el PIB per cápita) y valores democráticos (medido por un índice continúo construido por [V-Dem](https://www.v-dem.net/)). La base para el análisis la construiremos a partir de dos librerías `wbstats` que contiene la variable de **PIB per cápita** `(NY.GDP.PCAP.KD)` y `vdemdata` que contiene un índice generalmente aceptado sobre **Democracia** `(v2x_polyarchy)`.\n\nLa función para obtener la covarianza `cov()` y su sintaxis bastante sencilla, solo debo poner como argumentos a las dos variables que me interesa analizar.\\\nEste valor no tiene una interpretación analítica más allá de su signo, en el caso de democracia y PIB per cápita, como el valor es positivo, podemos afirmar que la democracia y el PIB se relacionan positivamente *(\"...a mayor PIB mayor democracia...\")*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Limpieza de ambiente\nrm(list = ls())   \n\n# Activacion de paquete tidyverse\nlibrary(tidyverse)\nlibrary(wbstats)\nlibrary(vdemdata)\n\n# Extraigo la variable de Banco Mundial\n\nbase <- wb_data(indicator = c(\"NY.GDP.PCAP.KD\"),\n                start_date = 2019,\n                end_date = 2019)\n\n# Extraigo la variable del paque vdemdata\n\nvarVdem <- c(\"country_text_id\",\n             \"year\",\n             \"v2x_polyarchy\")\n\n\nvdata <- vdemdata::vdem %>% \n  select(all_of(varVdem))\n\n# Join de bases\n\nbase <- base %>% \n  left_join(y = vdata,\n            by = c(\"iso3c\" = \"country_text_id\",\n                   \"date\" = \"year\"))\n\n# Eliminamos valores perdidos de la base\n\nbase <- base %>% \n  select(-c(unit, obs_status, footnote, last_updated)) %>% \n  na.omit()\n\n# Calculo de la covarianza\n\ncov(base$NY.GDP.PCAP.KD, base$v2x_polyarchy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2214.76\n```\n\n\n:::\n:::\n\n\nEste valor de covarianza tiene un correlato gráfico, cuando queremos ver gráficamente como se relacionan dos variables continuas, generamos lo que se conoce como gráfico de dispersión, el cual genera un diagrama de puntos del cual se puede inferir una pendiente (sentido), la cual puede ser positiva o negativa.\n\nA continuación se muestra el gráfico de dispersión entre `v2x_polyarchy` y `NY.GDP.PCAP.KD`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase %>% \n  ggplot(mapping = aes(x = (NY.GDP.PCAP.KD), y = v2x_polyarchy)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nEste es uno de esos casos donde se observa una relación (existe un patrón en los datos), pero esa relación no es tan clara, podríamos argumentar una relación positiva pero difícilmente podemos sostener que esa relación es completamente lineal.\n\n## Correlación\n\nLa covarianza nos permitió conocer que sí, que efectivamente existe una relación positiva entre democracia y PIB, sin embargo, no nos permitió conocer que tan fuerte es esa relación.\\\nNo lo permite porque la medida de la covarianza esta influenciada por las unidades de medición, es decir, el PIB se mide en miles de dólares y la democracia es un número índice entre cero y uno, como las unidades de medida son distintas, la covarianza no me dice nada respecto a la magnitud de la relación.\n\n::: {.callout-note appearance=\"simple\"}\n**¿Como solucionarlo?** con la Correlación. El cálculo de la correlación parte de la covarianza, pero agrega una división por los desvíos estándar de cada variable que normaliza el rango de valores posibles entre -1 y 1.\n:::\n\nEs decir, la correlación entre dos variables cualesquiera sean estas, es un valor entre -1 y 1, donde 1 significa una correlación positiva perfecta y -1 significa una correlación negativa perfecta.\\\nValores cercanos a cero indican que no existe una relación significativa entre las variables.\n\nFormalmente la fórmula de la correlación es:\n\n$$\\rho_{x,y} = \\frac{COV_{x,y}}{\\sigma_x\\cdot\\sigma_y} = \\frac{\\sum_{i=1}^n(x_i - \\bar{x})\\cdot(y_i - \\bar{y})}{\\sigma_x\\cdot\\sigma_y}$$\n\nNote en la fórmula matemática, que el valor del numerador es el mismo que en la fórmula de la covarianza, el cual habíamos deducido de la fórmula de la varianza.\n\nPara obtener la correlación entre dos variables, la lógica es muy similar a la de la covarianza, la función es `cor()` y los argumentos son los mismos, solo debo indicar las variables que estoy analizando.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(base$NY.GDP.PCAP.KD, base$v2x_polyarchy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4610839\n```\n\n\n:::\n:::\n\n\nEn ciencias sociales las correlaciones no tienden a ser muy fuertes, el valor de 0.46 entre democracia y PIB no es despreciable, me estaría indicando una intensidad media (no muy fuerte pero tampoco trivial) entre ambas variables.\n\nAlgo que puede ayudar en la discusión sobre la significatividad de la correlación, es utilizar un **test estadístico de correlación lineal**, el comando para realizarlo en R es `cor.test()`, los argumentos que recibe la función son los mismos que utilizamos en la función `cor()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(base$NY.GDP.PCAP.KD, base$v2x_polyarchy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  base$NY.GDP.PCAP.KD and base$v2x_polyarchy\nt = 6.755, df = 169, p-value = 2.204e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3341321 0.5716037\nsample estimates:\n      cor \n0.4610839 \n```\n\n\n:::\n:::\n\n\nEste test realiza una prueba de hipótesis, cuya hipótesis nula es que la verdadera correlación entre las variables es cero. Por lo tanto, para argumentar que la relación entre democracia y PIB per cápita es significativa, el objetivo es rechazar la hipótesis nula.\\\nEn la salida del comando `cor.test()`, se muestran dos criterios que nos permiten obtener conclusiones respecto a la hipótesis nula.\\\nEl primero es el ***p-value*** , en este caso su valor es de 2.2039961\\times 10^{-10}, por ser menor de 0.05, podemos rechazar la hipótesis nula y afirmar que la relación entre democracia y PIB per cápita es significativa.\\\nEl segundo son los ***intervalos de confianza***, cuando estos tienen el mismo signo, se puede rechazar la hipótesis nula, adémas, como en este caso son ambos positivos, podemos afirmar que la relación es significativa y positiva. (Límite inferior = 0.3341321, Límite superior = 0.5716037)\n\n### ¿Que agrega la correlación respecto a la covarianza?\n\nLa magnitud de la relación, por la covarianza yo sabía que la relación entre ambas variables era positiva, pero no sabía que tan positiva era. Ahora que tenemos la correlación, podemos afirmar que esa relación positiva es significativa (es distinta de cero) y está en torno al 0.46\n\nPodríamos ir un paso más allá y preguntarnos en cuanto mejoraría la democracia si incrementamos en una unidad el PIB per cápita.\\\nEste tipo de análisis ya es bastante más riguroso debido a que me permite hacer predicciones, es decir, podríamos conocer el valor del índice de democracia para un valor hipotético de $\\$ 50.000$ dólares de PIB.\\\nObviamente, esto tiene sus limitaciones, hay un montón de supuestos estadísticos detrás de la regresión que pocas veces se cumplen, pero es mejor saber hacerlo que simplemente no hacer nada porque ningún supuesto se cumple.\n\n## Regresión\n\nNo tengo pruebas pero tampoco dudas, de que la regresión es el análisis más utilizado para corroborar hipótesis en ciencias sociales.\\\nLo que vamos a ver ahora es un análisis de regresión simple, en el que existe una variable dependiente $(Y)$ y una variable independiente $(X)$. Lo de dependiente e independiente no es trivial, contrario a los análisis de covarianza y correlación, en el análisis de regresión si importa el orden y el sentido de la relación que planteo, puesto que estoy estableciendo una relación causal entre las variables en el sentido de que $(X)$ es causa de $(Y)$.\n\nRealizó el cálculo de la regresión para saber cuál sería el cambio en $(Y)$ si $(X)$ cambia en una unidad. La regresión tiene un apellido que es importante no olvidar, regresión **lineal**, este hace referencia a que se asume que la relación entre ambas variables $(X, Y)$ es lineal, es decir, existe una tasa constante que establece en cuanto se afecta $Y$ ante un cambio en $X$.\n\nLa fórmula más sencilla de regresión simple es:\n\n$$\\hat{y} = \\hat{\\alpha} + \\hat{\\beta}\\cdot x$$ Lo que establece el sentido de la relación entre $(X)$ y $(Y)$ es el valor de $\\hat{\\beta}$, cuya fórmula tiene que ver con la fórmula de la correlación y la covarianza.\n\n$$\\hat{\\beta} = \\frac{COV_{X,Y}}{VAR_X} = \\frac{\\sum_{i=1}^n(x_i - \\bar{x})\\cdot(y_i - \\bar{y})}{\\sum_{i=1}^n(x_i - \\bar{x})^2}$$\n\nLa regresión es la base de la inferencia causal, por eso es importante manejarla bien si mi objetivo es corroborar hipótesis entre variables, en el sentido de que una es causada por la otra.\n\nLa función para realizar análisis de regresión lineal simple es `lm()`, los argumentos también son dos variables pero la sintaxis es un poco diferente. Además, la impresión de los resultados requiere el uso de la función `summary()`, a continuación mostramos la regresión entre PIB per cápita e índice de democracia, es decir, asumimos que el PIB per cápita tiene un efecto positivo sobre el índice de democracia y queremos saber en cuanto cambiaria el índice de democracia si incrementamos en una unidad monetaria el PIB per cápita.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Para la regresion debemos usar el simbolo '~' de manera que antes de este se\n# encuentre la variable dependiente (Y) y despues de este se encuentre la variable \n# independiente (X).\n\nreg <- lm(formula = v2x_polyarchy ~ NY.GDP.PCAP.KD,\n          data = base)\n\n\n# Con la funcion 'summary()' veo el resultado de la regresion\n\nsummary(reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = v2x_polyarchy ~ NY.GDP.PCAP.KD, data = base)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.78694 -0.17709  0.04268  0.17469  0.37110 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    4.480e-01  2.092e-02  21.414  < 2e-16 ***\nNY.GDP.PCAP.KD 5.975e-06  8.845e-07   6.755  2.2e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.222 on 169 degrees of freedom\nMultiple R-squared:  0.2126,\tAdjusted R-squared:  0.2079 \nF-statistic: 45.63 on 1 and 169 DF,  p-value: 2.204e-10\n```\n\n\n:::\n:::\n\n\nAhora vemos muchos números y esto puede generar una mala impresión, lo relevante por ahora está en los `Coefficients`, donde vemos que existe un `(Intercept)` (equivalente a $\\hat{\\alpha}$ en la formula anterior) y el nombre de nuestra variable $(X)$ `NY.GDP.PCAP.KD` (equivalente a $\\hat{\\beta}$ en la formula anterior).\\\nCentrémonos en el valor del coeficiente de `NY.GDP.PCAP.KD`, este es de 5.97\\times 10^{-6}, parece muy bajito y cercano a cero, pero pensémoslo bien, lo que nos está diciendo es que si incremento el PIB per cápita en 1 dólar, el índice de democracia se incrementa en 5.97\\times 10^{-6}.\\\nUn cambio de un dólar en el PIB per cápita es algo casi que aleatorio, tendría mas sentido hablar de un cambio de mil dólares. Corrijamos la unidad de medida del PIB de manera que se refleje eso.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creo la variable de PIB per capita dividida por mil\n\nbase$pib <- base$NY.GDP.PCAP.KD/1000\n\n# Calculo nuevamente la regresión\n\nreg <- lm(formula = v2x_polyarchy ~ pib,\n          data = base)\n\nsummary(reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = v2x_polyarchy ~ pib, data = base)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.78694 -0.17709  0.04268  0.17469  0.37110 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.4479625  0.0209196  21.414  < 2e-16 ***\npib         0.0059747  0.0008845   6.755  2.2e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.222 on 169 degrees of freedom\nMultiple R-squared:  0.2126,\tAdjusted R-squared:  0.2079 \nF-statistic: 45.63 on 1 and 169 DF,  p-value: 2.204e-10\n```\n\n\n:::\n:::\n\n\nAl leer nuevamente los resultados, podemos concluir que un incremento de mil dólares en el PIB per cápita, conduce a un incremento en el valor del índice de democracia de 0.006, parece ínfimo, pero en ciencias sociales ese tipo de efectos son los más usuales.\\\nAlgo importante respecto a la lectura de los coeficientes es la última columna en la que aparece el P-Valor, lo que implícitamente hace el R, es una prueba de hipótesis en la que se corrobora si el valor de mi estimador (0.006) es significativamente diferente de 0.\\\nEl hecho de que el P-Valor sea menor que 0.001, implica que al $99.9\\%$ de confianza, el PIB tiene un efecto positivo sobre la democracia.\n\nLa regresión lineal también tiene un correlato gráfico, conocido como recta de regresión. A continuación se muestran dos opciones de código para graficarla con **{ggplot2}**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase %>% \n  ggplot(mapping = aes(x = pib, y = v2x_polyarchy)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") # Agrega la recta de regresión\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase %>% \n  ggplot(mapping = aes(x = pib, y = v2x_polyarchy)) +\n  geom_point() +\n  geom_abline(intercept = reg$coefficients[1], slope = reg$coefficients[2])\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n### ¿Como mejorar el ajuste?\n\nLa recta parece no ajustarse muy bien a los puntos, no se observa una distribución aleatoria de los puntos en torno a la recta de regresión.\\\nEn la clase pasada hablamos de la necesidad de que en ciertos escenarios, las variables presenten una distribución normal, el análisis de regresión es uno de ellos.\\\nEn el siguiente gráfico vemos la distribución de las variables Democracia y PIB per cápita, vemos que el PIB per cápita presenta un importante sesgo a la derecha, mientras la democracia no presenta un sesgo tan claro, pero es dificil sostener que tiene una distribución normal. Lo ideal sería poder corregir ambas distribuciones a partir de alguna transformación que conduzca a la variable a comportarse como una normal (o se aproxime más a ella).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase %>% \n  ggplot(mapping = aes(x = v2x_polyarchy)) + \n  geom_density() +\n  labs(title = \"Distribución v2x_polyarchy\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nbase %>% \n  ggplot(mapping = aes(x = pib)) + \n  geom_density() +\n  labs(title = \"Distribución PIB\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n:::\n\n\nLos logaritmos son las operaciones mas utilizadas para realizar este tipo de transformaciones, apliquemos logaritmo natural a ambas variables y veamos que pasa con el gráfico de dispersión y la recta de regresión.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase$log_democ <- log(base$v2x_polyarchy)\n\nbase$log_pib <- log(base$pib)\n\nreg_log <- lm(formula = log_democ ~ log_pib,\n              data = base)\n\n\nsummary(reg_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_democ ~ log_pib, data = base)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.6068 -0.2530  0.2628  0.3935  0.6520 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1.02715    0.07572 -13.566  < 2e-16 ***\nlog_pib      0.13505    0.03396   3.976 0.000104 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6246 on 169 degrees of freedom\nMultiple R-squared:  0.08555,\tAdjusted R-squared:  0.08014 \nF-statistic: 15.81 on 1 and 169 DF,  p-value: 0.0001036\n```\n\n\n:::\n:::\n\n\nCuando se utilizan logaritmos en ambas variables $(X,Y)$, la interpretación de la regresión pasa a realizarse en terminos porcentuales, es decir, en este caso un incremento del $1\\%$ en el PIB per cápita, generá un incremento del 0.135% en el índice de democracia.\n\nLa gráfica se ve asi ahora.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase %>% \n  ggplot(mapping = aes(x = log_pib, y = log_democ)) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nAunque el comportamiento sigue sin ser el ideal, mejoro significativamente respecto a sus valores originales.\n\n## Tabla resumen de las medidas calculadas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\nlibrary(kableExtra)\n\n# Datos de la tabla\ntabla <- data.frame(\n  Medida = c(\"Covarianza\", \"Correlación\", \"Regresión\"),\n  Interpretación = c(\"La relación entre las variables es (positiva/negativa)\", \n                     \"La relación entre las variables es (positiva/negativa) y significativa\", \n                     \"Un incremento de ... en X genera un cambio de ... en Y\"),\n  Fórmula = c(\"$$\\\\frac{\\\\sum_{i = 1}^n (x_i - \\\\bar{x}) \\\\cdot (y_i - \\\\bar{y})}{n-1}$$\",\n              \"$$\\\\frac{\\\\sum_{i=1}^n(x_i - \\\\bar{x}) \\\\cdot (y_i - \\\\bar{y})}{\\\\sigma_x \\\\cdot \\\\sigma_y}$$\",\n              \"$$\\\\frac{\\\\sum_{i=1}^n(x_i - \\\\bar{x}) \\\\cdot (y_i - \\\\bar{y})}{\\\\sum_{i=1}^n(x_i - \\\\bar{x})^2}$$\")\n)\n\n# Generar la tabla\nkable(tabla, format = \"html\", escape = FALSE, col.names = c(\"Medida\", \"Interpretación\", \"Fórmula\")) %>%\n  kable_styling(full_width = FALSE) %>%\n  add_header_above(c(\"Tabla Resumen\" = 3))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n<tr><th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; \" colspan=\"3\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">Tabla Resumen</div></th></tr>\n  <tr>\n   <th style=\"text-align:left;\"> Medida </th>\n   <th style=\"text-align:left;\"> Interpretación </th>\n   <th style=\"text-align:left;\"> Fórmula </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Covarianza </td>\n   <td style=\"text-align:left;\"> La relación entre las variables es (positiva/negativa) </td>\n   <td style=\"text-align:left;\"> $$\\frac{\\sum_{i = 1}^n (x_i - \\bar{x}) \\cdot (y_i - \\bar{y})}{n-1}$$ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Correlación </td>\n   <td style=\"text-align:left;\"> La relación entre las variables es (positiva/negativa) y significativa </td>\n   <td style=\"text-align:left;\"> $$\\frac{\\sum_{i=1}^n(x_i - \\bar{x}) \\cdot (y_i - \\bar{y})}{\\sigma_x \\cdot \\sigma_y}$$ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Regresión </td>\n   <td style=\"text-align:left;\"> Un incremento de ... en X genera un cambio de ... en Y </td>\n   <td style=\"text-align:left;\"> $$\\frac{\\sum_{i=1}^n(x_i - \\bar{x}) \\cdot (y_i - \\bar{y})}{\\sum_{i=1}^n(x_i - \\bar{x})^2}$$ </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}