{
  "hash": "715155b4e958f76a204b89240556f12d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Módulo 2: Análisis estadístico univariado\"\nauthor: \"Gerardo Esteban, Gómez-Santiago\"\ntoc: true\nformat: \n  html:\n    code-links:\n      - text: Video YouTube\n        icon: camera-reels\n        href: https://youtu.be/92DX5px65JI\n      - text: Repositorio GitHub\n        icon: file-code\n        href: https://github.com/GomezGerardoEsteban/Tidyverso/tree/main/TallerR/Modulo2\n    html-math-method: katex\n    code-tools: true\n    self-contained: true\nexecute:\n  warning: false\nimage: \"modulo2.png\"\n---\n\n## Introducción\n\nAnalizar datos consiste en gran medida en resumirlos, buscamos caracterizar a las observaciones a partir de medidas que resuman aspectos importantes o que nos generan interés.\\\nSiempre que se realiza un análisis estadístico, el primer paso está en conocer la distribución de los datos, buscamos determinar qué tan parecidos o que tan diferentes son las observaciones en una dimensión determinada (en estadística, dimensión es sinónimo de variable). Lo cual requiere calcular la media y la desviación estándar de la variable.\n\nLa media y la desviación estándar son los estadísticos más utilizados, pero no son los únicos que sirven para describir a los datos y, en algunas ocasiones, no son los más adecuados. La media por ejemplo, es una medida de posición que es sensible a datos atípicos, por lo que en algunas ocasiones resulta más conveniente utilizar la mediana o la moda. Igualmente, si bien la desviación estándar no tiene un sustituto en términos analíticos como medida de dispersión, muchas veces el rango de los datos (la diferencia entre el máximo y el mínimo) o el rango intercuartílico nos puede dar información más relevante sobre qué tan diferentes son las observaciones.\n\nSaber ejecutar los comandos para calcular la media, la desviación estándar o el valor máximo de una variable es importante y es el objetivo principal de este tutorial. Sin embargo, es igual de relevante conocer algo de teoría estadística a los fines de entender las implicaciones de estas medidas.\\\nUn buen material de texto, con ejemplos en R lo pueden encontrar en este link [Introduction to Statistics and Data Analysis](https://www.filepicker.io/api/file/TgilBNiCSk26axWSRDVA), lo que concierne a este módulo está en los capítulos 2 y 3 de este libro.\n\n## Que vamos a aprender en este módulo?\n\n-   Cómo calcular frecuencias absolutas y relativas\n-   Cómo calcular la media, la mediana y la moda\n-   Cómo calcular la varianza y la desviación estándar\n-   Cómo presentar estas medidas en tablas y gráficos\n\n## Frecuencias absolutas y relativas\n\nCuando tenemos variables categóricas en nuestra base de datos, una pregunta que siempre resulta necesario contestar es cuantas observaciones hay en una categoría y cuantas en otra, la base de datos de Latinobarómetro, con la cual trabajamos en el módulo 1 y la cual utilizaremos para este ejemplo, contiene muchas variables categóricas, por lo que la mayoría de los análisis consisten en conocer ***la proporción*** de personas que están de acuerdo o en desacuerdo con cierta afirmación.\n\nTomemos por ejemplo la variable `P18ST.A`, la cual almacena el grado de acuerdo con la afirmación *\"La democracia puede tener sus problemas pero es el mejor sistema de gobierno\"*, si logramos establecer cuantas personas están muy de acuerdo con esa afirmación por país, podríamos establecer en que países existe una mayor proporción de personas con valores democráticos.\\\nObtener el número de personas por respuesta, es lo que llamamos frecuencia absoluta. Si a esa frecuencia absoluta la dividimos por el total de personas que respondieron, obtenemos la frecuencia relativa.\n\n::: {.callout-note appearance=\"simple\"}\nLa frecuencia relativa es una proporción o porcentaje por lo que sus valores están acotados de 0 a 1 o de 0 a 100.\\\n\n$$Frecuencia \\hspace{0.1cm} relativa = \\frac{Frecuencia \\hspace{0.1cm} Absoluta}{Total \\hspace{0.1cm} de \\hspace{0.1cm} observaciones}$$\n:::\n\nObtengamos la frecuencia relativa por país y veamos cuales son los países que están más de acuerdo con esa afirmación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls()) # Limpieza de ambiente\n\n# Activacion de paquetes\n\nlibrary(foreign)\nlibrary(readxl)\nlibrary(tidyverse)\n\n# Carga de la base\n\nlatinBase <- read.dta(file = \"bases/Latinobarometro_2023_Esp_Stata_v1_0.dta\")\n```\n:::\n\n\n#### Creación de variable categórica\n\nComo la variable `P18ST_A` tiene varias respuestas posibles (utilizar función `unique()` para verificar), debemos crear una variable que tome el valor de **\"Acuerdo\"** si la respuesta es **Muy de acuerdo** o **De acuerdo**, de **\"Desacuerdo\"** si la respuesta es **En desacuerdo** o **Muy en desacuerdo** y **NA** si la respuesta es **No sabe/No responde**.\\\nA esta nueva variable le pondremos de nombre `democ`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verifico valores únicos\n\nunique(latinBase$P18ST_A) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] En desacuerdo         De acuerdo            Muy de acuerdo       \n[4] Muy en desacuerdo     No sabe / No contesta\n9 Levels: No sabe / No contesta No preguntada No aplicable ... Muy en desacuerdo\n```\n\n\n:::\n\n```{.r .cell-code}\n# Utilizó la función case_when()\n\nlatinBase$democ <- case_when(latinBase$P18ST_A == \"Muy de acuerdo\" | latinBase$P18ST_A == \"De acuerdo\" ~ \"Acuerdo\",\n                             latinBase$P18ST_A == \"Muy en desacuerdo\" | latinBase$P18ST_A == \"En desacuerdo\" ~ \"Desacuerdo\",\n                             latinBase$P18ST_A == \"No sabe / No contesta\" ~ NA)\n\n\n# Verifico valores únicos de la nueva variable\n\nunique(latinBase$democ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Desacuerdo\" \"Acuerdo\"    NA          \n```\n\n\n:::\n:::\n\n\n### Cálculo de frecuencias absolutas\n\nPara obtener una frecuencia relativa (la proporción de personas que están de acuerdo), primero debo obtener frecuencias absolutas, es decir, el número de personas que puedo categorizar como **\"Acuerdo\"**, **\"Desacuerdo\"** o **\"NA\"**.\\\nPara ello debo agrupar los datos con la función `group_by()` y posteriormente utilizar la función `summarize()`, `tally()` o `count()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# La función tally cuenta los valores respetando la agrupación y almacena el conteo con el nombre 'n'\n\nfrecuencias <- latinBase %>% \n  group_by(idenpa, democ) %>% \n  tally() \n\nfrecuencias\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 51 × 3\n# Groups:   idenpa [17]\n   idenpa       democ          n\n   <fct>        <chr>      <int>\n 1 \" Argentina\" Acuerdo      974\n 2 \" Argentina\" Desacuerdo   183\n 3 \" Argentina\" <NA>          43\n 4 \" Bolivia\"   Acuerdo      756\n 5 \" Bolivia\"   Desacuerdo   392\n 6 \" Bolivia\"   <NA>          52\n 7 \" Brasil\"    Acuerdo      909\n 8 \" Brasil\"    Desacuerdo   255\n 9 \" Brasil\"    <NA>          40\n10 \" Chile\"     Acuerdo      969\n# ℹ 41 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\n# Opcion con summarise()\n\nlatinBase %>% \n  group_by(idenpa, democ) %>% \n  summarise(frecAbs = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 51 × 3\n# Groups:   idenpa [17]\n   idenpa       democ      frecAbs\n   <fct>        <chr>        <int>\n 1 \" Argentina\" Acuerdo        974\n 2 \" Argentina\" Desacuerdo     183\n 3 \" Argentina\" <NA>            43\n 4 \" Bolivia\"   Acuerdo        756\n 5 \" Bolivia\"   Desacuerdo     392\n 6 \" Bolivia\"   <NA>            52\n 7 \" Brasil\"    Acuerdo        909\n 8 \" Brasil\"    Desacuerdo     255\n 9 \" Brasil\"    <NA>            40\n10 \" Chile\"     Acuerdo        969\n# ℹ 41 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\n# Opcion con count()\n\nlatinBase %>% \n  group_by(idenpa, democ) %>%\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 51 × 3\n# Groups:   idenpa, democ [51]\n   idenpa       democ          n\n   <fct>        <chr>      <int>\n 1 \" Argentina\" Acuerdo      974\n 2 \" Argentina\" Desacuerdo   183\n 3 \" Argentina\" <NA>          43\n 4 \" Bolivia\"   Acuerdo      756\n 5 \" Bolivia\"   Desacuerdo   392\n 6 \" Bolivia\"   <NA>          52\n 7 \" Brasil\"    Acuerdo      909\n 8 \" Brasil\"    Desacuerdo   255\n 9 \" Brasil\"    <NA>          40\n10 \" Chile\"     Acuerdo      969\n# ℹ 41 more rows\n```\n\n\n:::\n:::\n\n\nNote que hicimos la agrupación por dos variables (`idenpa` y `democ`), debido a que nuestro objetivo es obtener la frecuencia relativa por país.\n\n### Cálculo de frecuencias relativas\n\nPara obtener las frecuencias relativas por país, debemos obtener el total de personas por país y luego dividir la frecuencia absoluta en el total por país, en el código de abajo se muestra como agregar el total por país utilizando la misma sintaxis del paquete `{dplyr}`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrecuencias <- frecuencias %>% \n  ungroup() %>% \n  group_by(idenpa) %>% \n  mutate(total = sum(n, na.rm = T))\n```\n:::\n\n\nAhora tenemos una nueva variable de nombre `total` que nos muestra el total de observaciones por país, siguiendo lo antes formulado, para la frecuencia relativa debemos dividir `n` entre la variable `total`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrecuencias <- frecuencias %>% \n  mutate(frecRela = n/total)\n```\n:::\n\n\nYa calculamos las frecuencias relativas, por último, para comparar el grado de acuerdo de los países con la afirmación *\"La democracia puede tener sus problemas pero es el mejor sistema de gobierno\"*, vamos a filtrar a la base y a seleccionar solamente `latinBase$democ == \"Acuerdo\"`, organizandola de mayor a menor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrecuencias <- frecuencias %>% \n  filter(democ == \"Acuerdo\") %>% \n  arrange(desc(frecRela))\n\nfrecuencias\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 17 × 5\n# Groups:   idenpa [17]\n   idenpa             democ       n total frecRela\n   <fct>              <chr>   <int> <int>    <dbl>\n 1 \" Uruguay\"         Acuerdo  1019  1200    0.849\n 2 \" Argentina\"       Acuerdo   974  1200    0.812\n 3 \" Chile\"           Acuerdo   969  1200    0.808\n 4 \" El Salvador\"     Acuerdo   803  1000    0.803\n 5 \" Brasil\"          Acuerdo   909  1204    0.755\n 6 \" Costa Rica\"      Acuerdo   722  1000    0.722\n 7 \" Mexico\"          Acuerdo   857  1200    0.714\n 8 \" Rep. Dominicana\" Acuerdo   677  1000    0.677\n 9 \" Colombia\"        Acuerdo   757  1200    0.631\n10 \" Bolivia\"         Acuerdo   756  1200    0.63 \n11 \" Venezuela\"       Acuerdo   734  1201    0.611\n12 \" Paraguay\"        Acuerdo   705  1200    0.588\n13 \" Honduras\"        Acuerdo   553  1000    0.553\n14 \" Peru\"            Acuerdo   649  1200    0.541\n15 \" Guatemala\"       Acuerdo   521  1000    0.521\n16 \" Panama\"          Acuerdo   501  1000    0.501\n17 \" Ecuador\"         Acuerdo   593  1200    0.494\n```\n\n\n:::\n\n```{.r .cell-code}\n# Mayor acuerdo con la afirmación\nfrecuencias[1:3,c(1,5)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n# Groups:   idenpa [3]\n  idenpa       frecRela\n  <fct>           <dbl>\n1 \" Uruguay\"      0.849\n2 \" Argentina\"    0.812\n3 \" Chile\"        0.808\n```\n\n\n:::\n\n```{.r .cell-code}\n# Menor acuerdo con la afirmación\nfrecuencias[15:17, c(1,5)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n# Groups:   idenpa [3]\n  idenpa       frecRela\n  <fct>           <dbl>\n1 \" Guatemala\"    0.521\n2 \" Panama\"       0.501\n3 \" Ecuador\"      0.494\n```\n\n\n:::\n:::\n\n\n### Como interpretarlo?\n\nTomando al país con máximo grado de acuerdo y al país con mínimo grado de acuerdo podemos afirmar que, *\"En Uruguay el 84.9% de las personas considera que la democracia, aún con sus problemas es el mejor sistema de gobierno, mientras que en Ecuador solo el 49.4% está de acuerdo con esa afirmación\"*\n\n### Como exportarlo?\n\nYa construida la tabla de frecuencias que me informa sobre el porcentaje de acuerdo por país, puedo exportarla en excel, el comando para ello se muestra a continuación\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwritexl::write_xlsx(x = frecuencias,               # Nombre del objeto creado en R\n                    path = \"tablaFrecuencias.xlsx\") # Nombre del archivo a exportar\n```\n:::\n\n\n### Alternativa gráfica\n\nVamos a realizar un gráfico de barras (sin muchos detalles) que muestre la proporción por país y este organizado de mayor a menor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrecuencias %>% \n  ggplot(mapping = aes(x = frecRela, y = reorder(idenpa, frecRela))) +\n  geom_col()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Realización de mapa con dato de frecuencias\n\nLos mapas se han convertido en una alternativa de visualización cada vez más usada en ciencias sociales, por ello decidí incluir esta alternativa de visualización con los datos de la proporción de acuerdo con la afirmación *\"la democracia puede tener sus problemas, pero es el mejor sistema de gobierno\"*.\n\nNormalmente para gráficar mapas, es necesario tener algún archivo georeferenciado (como un archivo raster o un shapefile) que contenga la información a colocar en el mapa.\\\nPara este caso, que vamos a colorear a los países a partir de la variable de proporción, podemos utilizar la información geográfica que esta almacenada en el paquete `giscoR`\n\nLo primero entonces es instalar y activar esa librería\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Instalación de giscoR\n\n# install.packages(\"giscoR\")\n\n# Activación de giscoR\n\nlibrary(giscoR)\nlibrary(sf)\n```\n:::\n\n\nEste paquete contiene los poligonos de los paises, solo debemos asegurarnos de generar bien la información para no tener problemas al momento de pegar los datos\n\nDebemos asegurarnos que la base `frecuencias` la cual tiene la frecuencia relativa de acuerdo por país, este organizada de mayor a menor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrecuencias <- frecuencias %>% \n  arrange(-frecRela)\n```\n:::\n\n\nAñado el codigo ISO3 de los 17 paises que tengo, esto para poder pegar las proporciones a los datos geograficos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncode <- c(\"URY\", \"ARG\", \"CHL\", \n          \"SLV\", \"BRA\", \"CRI\", \n          \"MEX\", \"DOM\", \"COL\", \n          \"BOL\", \"VEN\", \"PRY\", \n          \"HND\", \"PER\", \"GTM\", \n          \"PAN\", \"ECU\")\n\nfrecuencias <- frecuencias %>% \n  ungroup() %>% \n  mutate(iso = code)\n\nfrecuencias\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 17 × 6\n   idenpa             democ       n total frecRela iso  \n   <fct>              <chr>   <int> <int>    <dbl> <chr>\n 1 \" Uruguay\"         Acuerdo  1019  1200    0.849 URY  \n 2 \" Argentina\"       Acuerdo   974  1200    0.812 ARG  \n 3 \" Chile\"           Acuerdo   969  1200    0.808 CHL  \n 4 \" El Salvador\"     Acuerdo   803  1000    0.803 SLV  \n 5 \" Brasil\"          Acuerdo   909  1204    0.755 BRA  \n 6 \" Costa Rica\"      Acuerdo   722  1000    0.722 CRI  \n 7 \" Mexico\"          Acuerdo   857  1200    0.714 MEX  \n 8 \" Rep. Dominicana\" Acuerdo   677  1000    0.677 DOM  \n 9 \" Colombia\"        Acuerdo   757  1200    0.631 COL  \n10 \" Bolivia\"         Acuerdo   756  1200    0.63  BOL  \n11 \" Venezuela\"       Acuerdo   734  1201    0.611 VEN  \n12 \" Paraguay\"        Acuerdo   705  1200    0.588 PRY  \n13 \" Honduras\"        Acuerdo   553  1000    0.553 HND  \n14 \" Peru\"            Acuerdo   649  1200    0.541 PER  \n15 \" Guatemala\"       Acuerdo   521  1000    0.521 GTM  \n16 \" Panama\"          Acuerdo   501  1000    0.501 PAN  \n17 \" Ecuador\"         Acuerdo   593  1200    0.494 ECU  \n```\n\n\n:::\n:::\n\n\nGuardo como `paises` una base que contiene los poligonos de los países, esta tiene la informacion geografica de todos los paises del mundo\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaises <- giscoR::gisco_countries\n\n# filtro por aquellos paises que estan en mis datos de proporcion\n\npaises <- paises %>% \n  filter(ISO3_CODE %in% code)\n```\n:::\n\n\nPego la proporcion a los datos geograficos\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaises <- paises %>% \n  left_join(y = frecuencias %>% \n              select(iso, frecRela), by = c(\"ISO3_CODE\" = \"iso\"))\n```\n:::\n\n\nRealizo la visulizacion del mapa\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmapa <- paises %>% \n  ggplot() +\n  geom_sf(mapping = aes(fill = frecRela)) +\n  scale_fill_continuous(type = \"viridis\") # Elijo una paleta que haga mas visibles las diferencias\n\nmapa\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nCon el comando `ggsave()` puedo exportar el mapa o cualquier grafico en formato imagen a mi directorio de trabajo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(filename = \"mapaDemoc.png\",\n       plot = mapa,\n       dpi = 500,\n       width = 5.48,\n       height = 4.29\n         )\n```\n:::\n\n\n## Medidas de posición\n\nEn variables cuantitativas, tenemos medidas de posición y medidas de dispersión, las medidas de posición buscan reflejar los valores más representativos de la variable, por ello la más utilizada y conocida es la media.\n\n### Media\n\nEn nuestro lenguaje natural esta incorporado hablar de promedios, lo cual está bien, en general busca reflejar cual es el valor más probable a observar. La función para calcular promedios en R es `mean()`, cuyo argumento indispensable es un conjunto de valores a promediar.\n\nPor ejemplo, el promedio de los números del 1 al 10 es 5.5 y la manera de obtenerlo en R es:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(1:10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5\n```\n\n\n:::\n:::\n\n\nMatemáticamente, un promedio se expresa como la suma de los valores dividido en el número total de valores. Es decir, lo que acabo de hacer el R es:\n\n$$mean = \\frac{1+2+3+4+5+6+7+8+9+10}{10}=\\frac{55}{10}=5.5$$\n\nOtra manera en la que se puede expresar lo anterior es:\n\n$$mean = \\frac{\\sum_{i = 1}^{10}x_i}{10} = \\frac{1}{10} \\cdot \\sum_{i=1}^{10}x_i$$\n\nAunque lo anterior es ilustrativo para reflejar lo que subyace a la función promedio, no solemos trabajar así, en general tenemos una base de datos y nos interesa obtener el promedio de algunas de las variables que la componen.\n\nPara ver esto utilicemos la base con nombre \"baseClase2.xlsx\", en esta base hay algunos indicadores del Banco Mundial sobre el desarrollo, previo a su análisis, hay algunas modificaciones de formato que debemos realizar (pasarla de formato ancho a largo), hecho eso, seleccionemos alguna de las variables y elijamos un subconjunto de países para calcular la media.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Levantamos la base con función read_excel() del paquete {readxl}\n\nbaseWB <- readxl::read_excel(path = \"bases/baseClase2.xlsx\")\n```\n:::\n\n\nAl utilizar la función `glimpse()`, vemos que los años aparecen como variables, si bien esto no esta mal conceptualmente, es necesario modificar su estructura para realizar ciertos análisis, la función a utilizar para ello es `gather()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseWB <- baseWB %>% # Pasamos de formato largo a ancho\n  gather(key = \"year\",     # Nombre de la variable que almacenara las columnas\n         value = \"valor\",  # Nombre de la variable con la que relleno los valores\n         5:ncol(baseWB))   # Columnas a pasar de ancho a lago\n```\n:::\n\n\nAhora tenemos una base de datos con 6 columnas, sin embargo, el número de variables contenidas en la base es mayor, la columna \"Indicator Name\" señala a que variable pertenece el valor, observando los valores únicos de \"Indicator Name\", vemos que en total son 11 variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(baseWB$`Indicator Name`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Cereal production (metric tons)\"                                                      \n [2] \"Gini index\"                                                                           \n [3] \"Human capital index (HCI) (scale 0-1)\"                                                \n [4] \"Intentional homicides (per 100,000 people)\"                                           \n [5] \"Life expectancy at birth, total (years)\"                                              \n [6] \"Multidimensional poverty headcount ratio (World Bank) (% of population)\"              \n [7] \"Physicians (per 1,000 people)\"                                                        \n [8] \"Population, total\"                                                                    \n [9] \"Poverty gap at $2.15 a day (2017 PPP) (%)\"                                            \n[10] \"Proportion of time spent on unpaid domestic and care work, female (% of 24 hour day)\" \n[11] \"Unemployment with advanced education (% of total labor force with advanced education)\"\n```\n\n\n:::\n:::\n\n\nPara finalmente tener una base de datos con una estructura tradicional, donde cada fila es una medición y cada columna es una variable, debemos hacer la transformación inversa a la realizada con `gather`, pero sobre la variable `Indicator Code` o `Indicator Name`, de esa forma tendremos a cada una de las 11 variables como una columna.\\\nPor practicidad en los nombres, utilizaremos a la variable `Indicator Code` pues esta no contiene caracteres especiales ni espacios.\n\nLa función que me permite hacer la operación inversa a `gather` es `spread`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseWB <- baseWB %>% \n  select(-`Indicator Name`) %>% \n  spread(key = `Indicator Code`, value = valor)\n\nbaseWB %>% glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 17,024\nColumns: 14\n$ `Country Name` <chr> \"Afghanistan\", \"Afghanistan\", \"Afghanistan\", \"Afghanist…\n$ `Country Code` <chr> \"AFG\", \"AFG\", \"AFG\", \"AFG\", \"AFG\", \"AFG\", \"AFG\", \"AFG\",…\n$ year           <chr> \"1960\", \"1961\", \"1962\", \"1963\", \"1964\", \"1965\", \"1966\",…\n$ AG.PRD.CREL.MT <dbl> NA, 3695000, 3696000, 3378000, 3732000, 3785000, 348900…\n$ HD.HCI.OVRL    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ SG.TIM.UWRK.FE <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ SH.MED.PHYS.ZS <dbl> 0.035, NA, NA, NA, NA, 0.063, NA, NA, NA, NA, 0.065, NA…\n$ SI.POV.GAPS    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ SI.POV.GINI    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ SI.POV.MPWB    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ SL.UEM.ADVN.ZS <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ SP.DYN.LE00.IN <dbl> 32.535, 33.068, 33.547, 34.016, 34.494, 34.953, 35.453,…\n$ SP.POP.TOTL    <dbl> 8622466, 8790140, 8969047, 9157465, 9355514, 9565147, 9…\n$ VC.IHR.PSRC.P5 <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n```\n\n\n:::\n:::\n\n\nAhora si tenemos nuestra base de datos con una estructura tradicional, siendo más precisos, tenemos un panel de datos, es decir, mediciones repetidas de las mismas unidades de observación (paises) en distintos momentos del tiempo.\n\nPara analizar el promedio, utilicemos la variable **\"Life expectancy at birth, total (years)\"**, esta variable esta medida desde 1990 y hasta 2021 para la mayoría de países, sin embargo, los valores de año aparecen desde 1960. Por simplicidad acotemos el análisis a algunos países, el código de la variable es `SP.DYN.LE00.IN`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Genero un vector a partir del cual filtrar la base\n# estos paises son los que voy a analizar\n\npaises <- c(\"MEX\", \"CRI\", \"COL\", \"URY\", \"PRY\", \"ARG\",\n            \"BRA\", \"USA\", \"JPN\", \"DEU\", \"CHL\", \"CAN\")\n```\n:::\n\n\nAhora calculemos el promedio de la expectativa de vida al nacer por país, es decir, promediemos los valores de cada país para los distintos años.\\\nPara ello debemos usar la función `group_by()` acompañada de la función `summarise()`, en la primera señalamos la variable categórica, en este caso país, a partir de la cual deseamos desagregar el análisis y en la segunda ponemos la medida a calcular, en este caso el nombre de la variable que es `SP.DYN.LE00.IN`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumenMedia <- baseWB %>%                                   # Base inicial\n  filter(`Country Code` %in% paises) %>%                            # filtro los paises que me interesan\n  group_by(`Country Code`) %>%                                      # agrupo por país  \n  summarise(mediaEspVida = mean(SP.DYN.LE00.IN))\n\nresumenMedia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   `Country Code` mediaEspVida\n   <chr>                 <dbl>\n 1 ARG                      NA\n 2 BRA                      NA\n 3 CAN                      NA\n 4 CHL                      NA\n 5 COL                      NA\n 6 CRI                      NA\n 7 DEU                      NA\n 8 JPN                      NA\n 9 MEX                      NA\n10 PRY                      NA\n11 URY                      NA\n12 USA                      NA\n```\n\n\n:::\n:::\n\n\nAl ejecutar el código vemos que muchas observaciones arrojan `NA` o valores perdidos, esto es porque para algunos años, esta variable no esta medida en esos países, la manera de solucionar ese problema es utilizando el argumento `'na.rm = T'` dentro de la función mean `mean(..., na.rm = T)`, con este argumento lo que hace R es tomar el promedio de los valores DISPONIBLES.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumenMedia <- baseWB %>%                                   # Base inicial\n  filter(`Country Code` %in% paises) %>%                            # filtro los paises que me interesan\n  group_by(`Country Code`) %>%                                      # agrupo por país  \n  summarise(mediaEspVida = mean(SP.DYN.LE00.IN, na.rm = T))\n\nresumenMedia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   `Country Code` mediaEspVida\n   <chr>                 <dbl>\n 1 ARG                    71.2\n 2 BRA                    65.6\n 3 CAN                    77.1\n 4 CHL                    71.6\n 5 COL                    68.6\n 6 CRI                    73.7\n 7 DEU                    75.5\n 8 JPN                    78.1\n 9 MEX                    68.2\n10 PRY                    67.5\n11 URY                    73.0\n12 USA                    74.9\n```\n\n\n:::\n:::\n\n\nLas conclusiones que podemos sacar de esta última tabla, es que Japón es el país que muestra mayor promedio en la expectativa de vida al nacer entre 1960 y 2021, mientras que Brasil es el país que muestra el valor más bajo.\n\n### Mediana\n\nLa mediana es el valor que, organizados los datos de menor a mayor, divide a los datos en dos partes iguales. Cuando existen valores atípicos (valores que se salen de la tendencia del resto de observaciones), la mediana es una mejor medida de posición, en el sentido que puede aportar una medida mas representativa del conjunto de los datos.\n\nLa lógica para obtenerla es la misma, y puede ser obtenida al tiempo que obtenemos la media, la función a utilizar es `median()`.\\\nA la tabla anterior con la media `resumenMedia`, añadiremos una columna que contenga la mediana.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumenMedia <- baseWB %>%                                   # Base inicial\n  filter(`Country Code` %in% paises) %>%                            # filtro los paises que me interesan\n  group_by(`Country Code`) %>%                                      # agrupo por país  \n  summarise(mediaEspVida = mean(SP.DYN.LE00.IN, na.rm = T),\n            medianaEspVida = median(SP.DYN.LE00.IN, na.rm = T))\n\nresumenMedia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 3\n   `Country Code` mediaEspVida medianaEspVida\n   <chr>                 <dbl>          <dbl>\n 1 ARG                    71.2           72.3\n 2 BRA                    65.6           66.3\n 3 CAN                    77.1           77.6\n 4 CHL                    71.6           73.6\n 5 COL                    68.6           68.8\n 6 CRI                    73.7           76.6\n 7 DEU                    75.5           75.3\n 8 JPN                    78.1           79.0\n 9 MEX                    68.2           70.1\n10 PRY                    67.5           68.2\n11 URY                    73.0           73.3\n12 USA                    74.9           75.4\n```\n\n\n:::\n:::\n\n\n### Graficando las medias obtenidas\n\nUna vez obtuvimos los resultados, una buena manera de presentarlos es a partir de un gráfico de barras que muestre el promedio por país y añadir una línea recta que muestre el promedio general, de manera que se pueda observar que países están por encima y que países están por debajo de la media general. Para hacer esto hay algo que hasta ahora no hemos obtenido, la media general.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmediaGeneral <- mean(baseWB$SP.DYN.LE00.IN[baseWB$`Country Code` %in% paises], na.rm = T)\n\nresumenMedia %>% \n  ggplot(mapping = aes(x = reorder(`Country Code`, desc(mediaEspVida)), y = mediaEspVida)) +\n  geom_col() +\n  geom_text(mapping = aes(label = round(mediaEspVida, 1)), # Añadimos valores a las columnas\n            nudge_y = 3) +\n  geom_hline(mapping = aes(yintercept = mediaGeneral), color = \"red\") # Añadimos media general en rojo\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nOtra manera de ver el comportamiento por país es a partir de un gráfico de cajas (boxplot), este mostraría no solo los valores centrales por país (puntualmente la mediana), sino la distribución por país para los distintos años.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseWB %>% \n  filter(`Country Code` %in% paises) %>%\n  group_by(`Country Code`) %>% \n  mutate(median = median(SP.DYN.LE00.IN, na.rm = T)) %>% \n  ggplot(mapping = aes(x = reorder(`Country Code`, desc(median)), y = SP.DYN.LE00.IN)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n## Medidas de dispersión\n\nSiempre es importante saber no solamente cual es el valor medio de una variable (medida de posición como media o mediana), sino también, que tanto se parecen cada uno de los datos a ese valor medio. Es decir, como se distribuyen los datos.\n\nA partir de las dos gráficas anteriores esto puede ser más intuitivo, en la gráfica de la media, vimos solamente la medida de posición (media) que le correspondía a cada país, de esta concluimos por ejemplo, que Japón es el que tiene mayor expectativa de vida al nacer y Brasil el que menos.\\\nSin embargo, viendo la segunda gráfica (gráfico de cajas) es posible ver que Brasil presento en algunos años valores por encima de 70 y en otros valores menores a 60. El hecho de que la caja de Brasil sea una de las más alargadas, implica que Brasil es uno de los países que muestra mayor dispersión en los datos.\n\nEl estadístico más usado para medir la dispersión de los datos, es la desviación estándar, el cual es la raíz cuadrada de la varianza. En general a mayor desviación estándar mayor variabilidad o dispersión de los datos y menos representativa resulta la media del conjunto de datos.\n\nPara obtener la desviación estandar la función a utilizar es `sd()`, su estructura de uso es idéntica a la que vimos con la media y con la mediana. Por ello añadiremos la desviación estandar como una columna adicional en `resumenMedia`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumenMedia <- baseWB %>%                                   # Base inicial\n  filter(`Country Code` %in% paises) %>%                            # filtro los paises que me interesan\n  group_by(`Country Code`) %>%                                      # agrupo por país  \n  summarise(mediaEspVida = mean(SP.DYN.LE00.IN, na.rm = T),\n            medianaEspVida = median(SP.DYN.LE00.IN, na.rm = T),\n            desvioEspVida = sd(SP.DYN.LE00.IN, na.rm = T))\n\nresumenMedia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n   `Country Code` mediaEspVida medianaEspVida desvioEspVida\n   <chr>                 <dbl>          <dbl>         <dbl>\n 1 ARG                    71.2           72.3          4.38\n 2 BRA                    65.6           66.3          6.96\n 3 CAN                    77.1           77.6          3.60\n 4 CHL                    71.6           73.6          7.35\n 5 COL                    68.6           68.8          5.64\n 6 CRI                    73.7           76.6          5.99\n 7 DEU                    75.5           75.3          3.98\n 8 JPN                    78.1           79.0          4.86\n 9 MEX                    68.2           70.1          6.16\n10 PRY                    67.5           68.2          4.06\n11 URY                    73.0           73.3          3.43\n12 USA                    74.9           75.4          2.96\n```\n\n\n:::\n:::\n\n\nFormalmente, la desviación estándar es la raíz de la suma de las distancias al cuadrado de cada observación con respecto a la media, en términos más llanos, refleja la distancia promedio de las observaciones con respecto al promedio.\n\nPor ejemplo, interpretando el dato de desviación estándar para Colombia, la distancia promedio de cada dato con respecto al promedio es de 5.64 años de expectativa de vida al nacer.\n\n$$\\sigma = \\sqrt{\\frac{\\sum_{i=1}^{n}(x_i - \\mu)\\cdot\\sum_{i=1}^{n}(x_i - \\mu)}{n-1}} = \\sqrt{\\frac{\\sum_{i=1}^{n}(x_i-\\mu)^2}{n-1}}$$\n\nUna manera de observar gráficamente la dispersión de los datos es a partir de histogramas, a continuación se presenta el histograma comparando a Colombia con Brasil y Japón.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseWB %>% \n  filter(`Country Name` %in% c(\"Colombia\", \"Brazil\", \"Japan\")) %>% \n  ggplot() +\n  geom_histogram(mapping = aes(x = SP.DYN.LE00.IN), \n                 bins = 15, \n                 color = \"black\",\n                 fill = \"lightgrey\") +\n  facet_wrap( ~ `Country Name`)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nOtra herramienta gráfica que suele utilizarse para ver a distribución de los datos, es la visualización de lo que se conoce como función de densidad. No profundizaremos demasiado al respecto, pero para que observen la lógica de la misma, se muestra la función de densidad de la expectativa de vida al nacer en 2019 para todos los países para los que existen datos, sobrepuesta al histograma.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseWB %>% \n  filter(year == 2019) %>% \n  ggplot(mapping = aes(x = SP.DYN.LE00.IN, y = ..density..)) +\n  geom_histogram(bins = 15,\n                 color = \"black\",\n                 fill = \"lightgrey\") +\n  geom_density(fill = \"blue\",\n               alpha = 0.15,\n               color = \"darkblue\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n## Otras medidas de dispersión\n\nAdemás de la desviación estándar, otras dos medidas que suelen presentarse son la varianza y el rango.\\\nLa varianza es el cuadrado de la desviación estandar, la cual se puede obtener con la funcion `var()` y el rango es la distancia entre el valor máximo y mínimo.\n\nA continuación añadimos estos valores en la tabla de `resumenMedia`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumenMedia <- baseWB %>%                                   # Base inicial\n  filter(`Country Code` %in% paises) %>%                            # filtro los paises que me interesan\n  group_by(`Country Code`) %>%                                      # agrupo por país  \n  summarise(mediaEspVida = mean(SP.DYN.LE00.IN, na.rm = T),         # obtengo la media\n            medianaEspVida = median(SP.DYN.LE00.IN, na.rm = T),     # obtengo la mediana \n            desvioEspVida = sd(SP.DYN.LE00.IN, na.rm = T),          # obtengo el desvio estandar\n            varEspVida = var(SP.DYN.LE00.IN, na.rm = T),            # obtengo la varianza\n            maxEspVida = max(SP.DYN.LE00.IN, na.rm = T),            # obtengo el maximo\n            minEspVida = min(SP.DYN.LE00.IN, na.rm = T))            # obtengo el minimo\n\nresumenMedia <- resumenMedia %>% \n  mutate(rango = maxEspVida - minEspVida)                           # obtengo el rango, la distancia entre el maximo y el minimo\n\nresumenMedia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 8\n   `Country Code` mediaEspVida medianaEspVida desvioEspVida varEspVida\n   <chr>                 <dbl>          <dbl>         <dbl>      <dbl>\n 1 ARG                    71.2           72.3          4.38      19.2 \n 2 BRA                    65.6           66.3          6.96      48.4 \n 3 CAN                    77.1           77.6          3.60      12.9 \n 4 CHL                    71.6           73.6          7.35      54.1 \n 5 COL                    68.6           68.8          5.64      31.9 \n 6 CRI                    73.7           76.6          5.99      35.9 \n 7 DEU                    75.5           75.3          3.98      15.8 \n 8 JPN                    78.1           79.0          4.86      23.6 \n 9 MEX                    68.2           70.1          6.16      38.0 \n10 PRY                    67.5           68.2          4.06      16.4 \n11 URY                    73.0           73.3          3.43      11.7 \n12 USA                    74.9           75.4          2.96       8.78\n# ℹ 3 more variables: maxEspVida <dbl>, minEspVida <dbl>, rango <dbl>\n```\n\n\n:::\n:::\n\n\n## Una alternativa para el análisis\n\nHasta ahora nos hemos concentrado en desagregar el análisis por países, una alternativa valida para el análisis es deasagregar la información por años, de manera que podamos observar la tendencia promedio de la expectativa de vida al nacer.\n\nRealizaremos una tabla resumen que presente esa información, la estructura del código con `group_by()` y `summarise()` es la misma, pero, en lugar de agrupar la información por países debemos agruparla por año.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumenAnios <-  baseWB %>% \n  filter(year != 2023) %>% \n  group_by(year) %>% \n  summarise(mediaEspVida = mean(SP.DYN.LE00.IN, na.rm = T),\n            medianaEspVida = median(SP.DYN.LE00.IN, na.rm = T),\n            desvioEspVida = sd(SP.DYN.LE00.IN, na.rm = T),\n            varEspVida = var(SP.DYN.LE00.IN, na.rm = T),\n            maxEspVida = max(SP.DYN.LE00.IN, na.rm = T),\n            minEspVida = min(SP.DYN.LE00.IN, na.rm = T))\n\n\nprint(resumenAnios, n = 70) # Con este comando veo todo el resultado en mi consola\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 63 × 7\n   year  mediaEspVida medianaEspVida desvioEspVida varEspVida maxEspVida\n   <chr>        <dbl>          <dbl>         <dbl>      <dbl>      <dbl>\n 1 1960          53.5           53.9         11.5       133.        73.8\n 2 1961          54.2           54.4         11.3       128.        73.7\n 3 1962          54.8           55.2         11.0       122.        73.7\n 4 1963          55.1           55.7         11.0       121.        73.6\n 5 1964          55.7           56.3         11.0       120.        73.7\n 6 1965          56.0           56.9         11.0       121.        73.9\n 7 1966          56.4           57.6         11.0       120.        74.1\n 8 1967          56.9           58.1         10.9       119.        74.1\n 9 1968          57.2           58.4         10.7       115.        74.0\n10 1969          57.4           58.6         10.7       115.        74.1\n11 1970          57.7           59.0         10.8       116.        74.6\n12 1971          58.1           59.6         10.8       117.        74.6\n13 1972          58.6           60.1         10.6       113.        74.7\n14 1973          59.2           60.4         10.4       107.        74.9\n15 1974          59.4           60.8         10.3       106.        75.0\n16 1975          59.7           61.1         10.8       116.        75.6\n17 1976          59.9           61.6         10.9       118.        77.0\n18 1977          60.6           62.0         10.3       106.        76.4\n19 1978          61.0           62.5         10.2       105.        76.6\n20 1979          61.3           62.9         10.0       101.        76.8\n21 1980          61.7           63.4          9.80       96.0       76.8\n22 1981          62.1           63.8          9.79       95.8       76.5\n23 1982          62.3           64.2          9.82       96.4       77.0\n24 1983          62.6           64.6          9.87       97.4       76.9\n25 1984          62.9           65.2          9.98       99.6       77.6\n26 1985          63.2           65.7          9.91       98.2       77.6\n27 1986          63.7           66.1          9.83       96.6       78.0\n28 1987          63.9           66.4          9.96       99.3       78.4\n29 1988          64.0           66.8         10.3       105.        78.3\n30 1989          64.5           67.2          9.64       93.0       78.8\n31 1990          64.7           67.5          9.69       93.9       78.8\n32 1991          64.8           67.7          9.89       97.9       79.0\n33 1992          64.9           67.8         10.1       102.        79.1\n34 1993          65.1           67.7          9.92       98.5       79.3\n35 1994          65.4           67.8          9.93       98.7       79.7\n36 1995          65.6           67.9          9.66       93.4       79.5\n37 1996          65.8           68.7          9.77       95.5       80.2\n38 1997          66.0           68.8          9.82       96.5       80.4\n39 1998          66.1           69.1         10.2       104.        80.7\n40 1999          66.5           69.3          9.81       96.3       81.5\n41 2000          67.0           69.7          9.55       91.3       81.4\n42 2001          67.3           69.9          9.59       92.0       81.4\n43 2002          67.6           70.3          9.49       90.1       81.7\n44 2003          67.9           70.3          9.36       87.6       81.8\n45 2004          68.2           70.7          9.33       87.1       82.0\n46 2005          68.5           71.0          9.17       84.2       82.0\n47 2006          68.9           71.1          9.04       81.6       82.4\n48 2007          69.2           71.3          8.89       78.9       82.5\n49 2008          69.5           71.5          8.78       77.2       82.9\n50 2009          69.9           71.8          8.60       74.0       83.3\n51 2010          70.3           72.1          8.58       73.6       83.1\n52 2011          70.7           72.3          8.30       68.9       83.4\n53 2012          71.0           72.4          8.12       66.0       83.5\n54 2013          71.2           72.7          7.98       63.7       83.8\n55 2014          71.5           72.9          7.93       62.8       83.9\n56 2015          71.7           73.1          7.72       59.6       84.3\n57 2016          72.0           73.3          7.60       57.7       84.2\n58 2017          72.2           73.6          7.49       56.1       84.7\n59 2018          72.4           73.6          7.40       54.8       84.9\n60 2019          72.7           73.6          7.34       53.9       85.2\n61 2020          72.0           72.7          7.27       52.9       85.5\n62 2021          71.4           72.0          7.44       55.4       85.5\n63 2022          72.1           73.2          7.50       56.2       85.4\n# ℹ 1 more variable: minEspVida <dbl>\n```\n\n\n:::\n:::\n\n\nDe esta tabla que contiene el promedio general por año, podemos generar un gráfico en el que observemos como se ha comportado la misma a lo largo del tiempo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumenAnios <- resumenAnios %>% \n  mutate(year = as.numeric(year)) # La variable 'year' esta almacenada como tipo <chr> (character = almacena texto)\n                                  # para grafical la tendenia debo transformarla en numerica.   \n\n\n# Genero un grafico de linea que muestra la tendencia\n\nresumenAnios %>% \n  ggplot(mapping = aes(x = year, y = mediaEspVida)) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nLa tendencia es positiva, por lo tanto, es posible afirmar que la expectativa de vida al nacer es una variable que ha mejorado con el tiempo alrededor del mundo.\\\nSi además profundizamos el análisis de la media y la desviación estándar por año, no solo la media crecio, sino que la desviación estándar se redujo, lo que quiere decir que en general, todos los países están mejor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumenAnios %>% \n  select(year, mediaEspVida, desvioEspVida) %>% \n  filter(year %in% c(1960,2022))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n   year mediaEspVida desvioEspVida\n  <dbl>        <dbl>         <dbl>\n1  1960         53.5         11.5 \n2  2022         72.1          7.50\n```\n\n\n:::\n:::\n\n\n## Una digresión sobre la distribución normal\n\nEn general, quien ha tomado un curso de estadística alguna vez, ha escuchado sobre la distribución normal o distribución normal estándar. Introduzco este tema acá, porque en muchos de nuestros análisis, asumimos que los datos se distribuyen de manera normal, aunque empíricamente no sea así. Por ejemplo, si los datos de la expectativa de vida al nacer que acabamos de graficar, tuvieran una distribución normal, tendrían que verse más o menos así:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseN <- baseWB %>% \n  filter(year == 2019)\n\ndf <- tibble(variable = rnorm(n = 1000, mean = mean(baseN$SP.DYN.LE00.IN, na.rm = T), sd = sd(baseN$SP.DYN.LE00.IN, na.rm = T)))\n\ndf %>% \n  ggplot(mapping = aes(x = variable, y = ..density..)) +\n  geom_histogram(bins = 15,\n                 color = \"black\",\n                 fill = \"lightgrey\") +\n    geom_density(fill = \"blue\",\n               alpha = 0.15,\n               color = \"darkblue\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nEsta forma acampanada es la que frecuentemente asumimos tiene la distribución de nuestros datos, la diferencia con respecto a la verdadera distribución es innegable, no ampliaremos demasiado sobre esto, pero es importante conocer de que se habla cuando se dice que una variable tiene una distribución normal y que en muchos de nuestros análisis se asume que los datos tienen una distribución normal.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}